In [18]:
Alpha_Name = "AlphaNetV4_LSTM"
sequence = 20
shift=1
LR = [0.001,0.00001,0.0000001]
epoch_num = [30,30,30]
feature_num = 103
target = "10dRet"

In [19]:
alpha_list = pd.read_parquet("/home/wuwenjun/Data/AlphaNetV4_Moving10/2016/20160118.par").columns
alpha_list

Index(['COV_div_open_close_div_high_close_10',
       'COV_div_open_close_div_low_close_10', 'COV_div_open_close_close_10',
       'COV_div_open_close_volume_sqrt_8_10', 'COV_div_open_close_pct_chg_10',
       'COV_div_open_close_div_close_free_turnover_10',
       'COV_div_open_close_div_low_high_10',
       'COV_div_high_close_div_low_close_10', 'COV_div_high_close_close_10',
       'COV_div_high_close_volume_sqrt_8_10',
       ...
       'RETURN_div_price_turnover_10', 'RETURN_div_low_high_10',
       'RETURN_div_vwap_close_2_10', 'DECAY_div_high_close_10',
       'DECAY_div_low_close_10', 'DECAY_volume_sqrt_8_10',
       'DECAY_div_close_free_turnover_10', 'DECAY_div_price_turnover_10',
       'DECAY_div_low_high_10', 'DECAY_div_vwap_close_2_10'],
      dtype='object', length=103)

In [20]:
import pandas as pd
import numpy as np
task_info = np.load("/home/ShareFolder/feature_platform/ti0/wuwenjun/#Factor_Description/Task.npy",allow_pickle=True).item()
# pd.read_parquet("/home/ShareFolder/feature_platform/ti0/wuwenjun/#Factor_Description/Task.par")
original = task_info["Task"]
original

,Alpha_Name,sequence,LR,epoch_num,feature_num,start_date,end_date,status,description
task_id,,,,,,,,,
0,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2019-01-01,2019-06-01,finished,None
1,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2019-06-01,2020-01-01,finished,None
2,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2020-01-01,2020-06-01,finished,None
3,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2020-06-01,2021-01-01,finished,None
4,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2021-01-01,2021-06-01,finished,None
...,...,...,...,...,...,...,...,...,...
210,AlphaNetV4_Moving10_Shift_1_Sequence_20_10dRet,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2019-01-01,2019-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
211,AlphaNetV4_Moving10_Shift_1_Sequence_20_10dRet,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2019-06-01,2020-01-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
212,AlphaNetV4_Moving10_Shift_1_Sequence_20_10dRet,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2020-01-01,2020-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
213,AlphaNetV4_Moving10_Shift_1_Sequence_20_10dRet,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2020-06-01,2021-01-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
214,AlphaNetV4_Moving10_Shift_1_Sequence_20_10dRet,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2021-01-01,2021-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."

In [21]:
time_list = ["2019-01-01","2019-06-01","2020-01-01","2020-06-01","2021-01-01","2021-06-01"]
time_list2 = []
for i in range(len(time_list)-1):
    time_list2.append([time_list[i],time_list[i+1]])
time_list2 = pd.DataFrame(time_list2,columns=["start_date","end_date"])
time_list2

   start_date    end_date
0  2019-01-01  2019-06-01
1  2019-06-01  2020-01-01
2  2020-01-01  2020-06-01
3  2020-06-01  2021-01-01
4  2021-01-01  2021-06-01

In [28]:
np.load("/home/wuwenjun/Alpha_Factor/AlphaNet_8Input_corr_filter_Shift_1_Sequence_20_10dRet/2019-01-01_2019-06-01/loss.npy")

array([0.57934243, 0.55207747, 0.52696934, 0.49969886, 0.47439853,
       0.45336702, 0.43455319, 0.41826427, 0.4040433 , 0.39296041,
       0.38109183, 0.37197185, 0.36356464, 0.35567691, 0.3481858 ,
       0.34210614, 0.33554037, 0.32982299, 0.32555381, 0.32074804,
       0.31702691, 0.31238767, 0.30935971, 0.30536713, 0.30207075,
       0.30035645, 0.29662787, 0.29441012, 0.29262382, 0.28934172,
       0.27730972, 0.2726818 , 0.26973677, 0.26789194, 0.26708166,
       0.26573829, 0.26474713, 0.26439475, 0.26358444, 0.26294294,
       0.26233304, 0.26165151, 0.26170538, 0.26059564, 0.26067971,
       0.26017303, 0.25964815, 0.2595774 , 0.25959902, 0.25923058,
       0.258354  , 0.25857349, 0.25863821, 0.25785379, 0.25795155,
       0.25762701, 0.25767483, 0.25714469, 0.25657626, 0.25692783])

In [22]:
task = pd.DataFrame([Alpha_Name,sequence,LR,epoch_num,feature_num],index=["Alpha_Name","sequence","LR","epoch_num","feature_num"]).T
task['value']=1
time_list2['value']=1
task = pd.merge(task,time_list2,how='left',on='value')
del task['value']
task["status"] = "waiting"
task["description"] = [{
    "target" : target,
    "alpha_name" : Alpha_Name,
    "alpha_list" : alpha_list,
    "shift" : shift,
    "sequence" : sequence
} for i in range(len(task))]
task

,Alpha_Name,sequence,LR,epoch_num,feature_num,start_date,end_date,status,description
0,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2019-01-01,2019-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
1,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2019-06-01,2020-01-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
2,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2020-01-01,2020-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
3,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2020-06-01,2021-01-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
4,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2021-01-01,2021-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."

In [24]:
task = pd.concat([original,task],axis=0)
task.reset_index(drop=True,inplace=True)
task.index.names = ["task_id"]
task_info["Task"] = task
# if task.duplicated().any() == True:
#     task = original
#     raise ValueError("concains duplicates value")
task

,Alpha_Name,sequence,LR,epoch_num,feature_num,start_date,end_date,status,description
task_id,,,,,,,,,
0,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2019-01-01,2019-06-01,finished,None
1,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2019-06-01,2020-01-01,finished,None
2,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2020-01-01,2020-06-01,finished,None
3,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2020-06-01,2021-01-01,finished,None
4,Original_Input_Moving_10_Shift_5,5,"[0.001, 0.0001]","[30, 20]",108,2021-01-01,2021-06-01,finished,None
...,...,...,...,...,...,...,...,...,...
215,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2019-01-01,2019-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
216,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2019-06-01,2020-01-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
217,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2020-01-01,2020-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
218,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2020-06-01,2021-01-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."
219,AlphaNetV4_LSTM,20,"[0.001, 1e-05, 1e-07]","[30, 30, 30]",103,2021-01-01,2021-06-01,waiting,"{'target': '10dRet', 'alpha_name': 'AlphaNetV4..."

In [25]:
task_info["Cuda"]

['cuda:1', 'cuda:1', 'cuda:0', 'cuda:0']

In [26]:
np.save("/home/ShareFolder/feature_platform/ti0/wuwenjun/#Factor_Description/Task.npy",task_info)