In [1]:
import time
import os
from Research.backtest.bt import BTDaily
from Research.feature.ft import FeatureAnalysis
import Research.utils.namespace as namespace
import Research.utils.normalization as norm
from Platform.database.mysql import MysqlAPI
from Platform.utils.persistence import convert_to_standard_daily_feature_csv, convert_to_standard_daily_feature_par
from Platform.config.mysql_info import FACTOR_LIB_MYSQL_TIO
import DataAPI
from os import walk
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from progressbar import ProgressBar
from tqdm import tqdm
import multiprocessing as mp
import sys
sys.path.append("/home/wuwenjun/jupyter_code/Shannon/AlphaNet/packages/")

In [2]:
from AlphaNet.Data import DataLoader

In [3]:
dataloader = DataLoader()

In [4]:
dataloader.load_data_from_file(data_path="/home/wuwenjun/Data_lib/ti0/wuwenjun/test/",end_date="2022-01-01")

                            test_mcorr_open_low_10    test_1     test  \
timestamp           ticker
2020-01-02 09:30:00 000001                0.115025  0.115025  3604.78
                    000002                0.796874  0.796874  9428.61
                    000004                0.815852  0.815852   184.01
                    000005                0.815519  0.815519    57.28
                    000006                0.846951  0.846951   379.05
...                                            ...       ...      ...
2021-06-01 09:30:00 688699                     NaN       NaN      NaN
                    688777                     NaN       NaN      NaN
                    688788                     NaN       NaN      NaN
                    688819                     NaN       NaN      NaN
                    688981                     NaN       NaN      NaN

                            ewmCorr(high,low)  ewmCorr(high,low,7)    target
timestamp           ticker
2020-01-02 09:30:00 000001           0.414245             0.414245 -5.551395
                    000002           0.968666             0.968666 -6.203258
                    000004          -0.086929            -0.086929 -5.390784
                    000005           0.656316             0.656316 -5.142255
                    000006           0.967827             0.967827 -5.327572
...                                       ...                  ...       ...
2021-06-01 09:30:00 688699                NaN                  NaN -6.236975
                    688777                NaN                  NaN -6.432447
                    688788                NaN                  NaN -6.486812
                    688819                NaN                  NaN -6.124710
                    688981                NaN                  NaN -6.088935

[1366034 rows x 6 columns]

In [10]:
shift = 7

In [18]:
sequence_list = [0]
for i in range(shift-1,30,shift):
    sequence_list.append(i)
sequence_list.sort(reverse=True)
sequence_list

[27, 20, 13, 6, 0]

In [17]:
x = dataloader.feature_data.drop("target",axis=1)
x

                            test_mcorr_open_low_10    test_1     test  \
timestamp           ticker
2020-01-02 09:30:00 000001                0.115025  0.115025  3604.78
                    000002                0.796874  0.796874  9428.61
                    000004                0.815852  0.815852   184.01
                    000005                0.815519  0.815519    57.28
                    000006                0.846951  0.846951   379.05
...                                            ...       ...      ...
2021-06-01 09:30:00 688699                     NaN       NaN      NaN
                    688777                     NaN       NaN      NaN
                    688788                     NaN       NaN      NaN
                    688819                     NaN       NaN      NaN
                    688981                     NaN       NaN      NaN

                            ewmCorr(high,low)  ewmCorr(high,low,7)
timestamp           ticker
2020-01-02 09:30:00 000001           0.414245             0.414245
                    000002           0.968666             0.968666
                    000004          -0.086929            -0.086929
                    000005           0.656316             0.656316
                    000006           0.967827             0.967827
...                                       ...                  ...
2021-06-01 09:30:00 688699                NaN                  NaN
                    688777                NaN                  NaN
                    688788                NaN                  NaN
                    688819                NaN                  NaN
                    688981                NaN                  NaN

[1366034 rows x 5 columns]

In [20]:
final_df = []
for index,group in (x.groupby("ticker")):
    group_df = []
    for i in sequence_list:
        a = group.shift(i)
        a.columns = [str(j)+"_Shift_%i" % i for j in group.columns]
        group_df.append(a)
    group_df = pd.concat(group_df,axis=1)
    final_df.append(group_df)
final_df = pd.concat(final_df,axis=0)
final_df

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000001,0.691493,0.691493,4608.52,0.711368,0.711368
2021-05-27 09:30:00,000001,0.803294,0.803294,4604.08,0.730593,0.730593
2021-05-28 09:30:00,000001,0.846976,0.846976,4566.32,0.826351,0.826351
2021-05-31 09:30:00,000001,0.885159,0.885159,4510.80,0.950763,0.950763
2021-06-01 09:30:00,000001,0.890170,0.890170,4572.99,0.228314,0.228314

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000001,0.956342,0.956342,5127.12,0.958211,0.958211
2021-05-27 09:30:00,000001,0.973428,0.973428,5175.98,0.969230,0.969230
2021-05-28 09:30:00,000001,0.977260,0.977260,5198.19,0.587066,0.587066
2021-05-31 09:30:00,000001,0.976917,0.976917,5096.03,0.391034,0.391034
2021-06-01 09:30:00,000001,0.976615,0.976615,5179.31,0.359478,0.359478

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000001,0.930698,0.930698,5174.87,0.782386,0.782386
2021-05-27 09:30:00,000001,0.738845,0.738845,5299.24,0.988056,0.988056
2021-05-28 09:30:00,000001,0.288756,0.288756,5314.79,0.662902,0.662902
2021-05-31 09:30:00,000001,0.225205,0.225205,5235.95,0.579878,0.579878
2021-06-01 09:30:00,000001,0.272381,0.272381,5201.52,0.810927,0.810927

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000001,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000001,0.121460,0.121460,5232.35,0.988231,0.988231
2021-05-27 09:30:00,000001,0.508842,0.508842,5344.27,0.976004,0.976004
2021-05-28 09:30:00,000001,0.612502,0.612502,5307.34,0.955207,0.955207
2021-05-31 09:30:00,000001,0.614737,0.614737,5286.07,0.900928,0.900928
2021-06-01 09:30:00,000001,0.571106,0.571106,5301.75,-0.336042,-0.336042

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000001,0.115025,0.115025,3604.78,0.414245,0.414245
2020-01-03 09:30:00,000001,0.340535,0.340535,3659.36,0.922935,0.922935
2020-01-06 09:30:00,000001,0.717011,0.717011,3724.86,0.989700,0.989700
2020-01-07 09:30:00,000001,0.820196,0.820196,3720.49,0.987041,0.987041
2020-01-08 09:30:00,000001,0.931442,0.931442,3742.33,0.893703,0.893703
...,...,...,...,...,...,...
2021-05-26 09:30:00,000001,0.662165,0.662165,5387.92,0.853938,0.853938
2021-05-27 09:30:00,000001,0.861243,0.861243,5556.93,0.846581,0.846581
2021-05-28 09:30:00,000001,0.918978,0.918978,5562.53,0.881541,0.881541
2021-05-31 09:30:00,000001,0.925947,0.925947,5504.32,0.871969,0.871969
2021-06-01 09:30:00,000001,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000002,0.919487,0.919487,8770.80,0.995058,0.995058
2021-05-27 09:30:00,000002,0.918394,0.918394,8796.96,0.931156,0.931156
2021-05-28 09:30:00,000002,0.946333,0.946333,8815.43,0.919531,0.919531
2021-05-31 09:30:00,000002,0.935363,0.935363,8873.91,0.246338,0.246338
2021-06-01 09:30:00,000002,0.917960,0.917960,8900.08,0.147168,0.147168

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000002,0.706390,0.706390,8901.62,0.930528,0.930528
2021-05-27 09:30:00,000002,0.675850,0.675850,8709.24,0.989890,0.989890
2021-05-28 09:30:00,000002,0.863904,0.863904,8572.27,0.989498,0.989498
2021-05-31 09:30:00,000002,0.923654,0.923654,8552.26,0.958404,0.958404
2021-06-01 09:30:00,000002,0.949711,0.949711,8559.96,0.916661,0.916661

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000002,0.941573,0.941573,8586.12,0.986009,0.986009
2021-05-27 09:30:00,000002,0.906922,0.906922,8604.59,0.988560,0.988560
2021-05-28 09:30:00,000002,0.834284,0.834284,8546.10,0.965872,0.965872
2021-05-31 09:30:00,000002,0.757059,0.757059,8453.77,0.957946,0.957946
2021-06-01 09:30:00,000002,0.796386,0.796386,8376.82,0.966537,0.966537

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000002,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000002,0.918233,0.918233,8333.73,0.912367,0.912367
2021-05-27 09:30:00,000002,0.917287,0.917287,8382.97,0.712899,0.712899
2021-05-28 09:30:00,000002,0.862096,0.862096,8321.41,0.392548,0.392548
2021-05-31 09:30:00,000002,0.866871,0.866871,8253.69,0.937406,0.937406
2021-06-01 09:30:00,000002,0.860889,0.860889,8238.30,0.873623,0.873623

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000002,0.796874,0.796874,9428.61,0.968666,0.968666
2020-01-03 09:30:00,000002,0.909067,0.909067,9700.20,0.987860,0.987860
2020-01-06 09:30:00,000002,0.895624,0.895624,9611.15,0.989240,0.989240
2020-01-07 09:30:00,000002,0.911692,0.911692,9388.54,0.973091,0.973091
2020-01-08 09:30:00,000002,0.916477,0.916477,9404.86,0.973601,0.973601
...,...,...,...,...,...,...
2021-05-26 09:30:00,000002,0.882132,0.882132,8153.66,0.643474,0.643474
2021-05-27 09:30:00,000002,0.837016,0.837016,8299.86,0.970997,0.970997
2021-05-28 09:30:00,000002,0.867985,0.867985,8364.50,0.754224,0.754224
2021-05-31 09:30:00,000002,0.873714,0.873714,8327.56,0.651700,0.651700
2021-06-01 09:30:00,000002,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000004,0.822715,0.822715,145.85,-0.874100,-0.874100
2021-05-27 09:30:00,000004,0.981807,0.981807,156.21,0.906397,0.906397
2021-05-28 09:30:00,000004,0.986204,0.986204,151.54,0.552110,0.552110
2021-05-31 09:30:00,000004,0.966449,0.966449,151.50,0.534251,0.534251
2021-06-01 09:30:00,000004,0.967462,0.967462,154.75,0.411539,0.411539

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000004,0.966402,0.966402,149.59,0.872014,0.872014
2021-05-27 09:30:00,000004,0.959397,0.959397,150.48,0.201303,0.201303
2021-05-28 09:30:00,000004,0.940047,0.940047,149.43,0.400431,0.400431
2021-05-31 09:30:00,000004,0.812867,0.812867,144.55,0.928352,0.928352
2021-06-01 09:30:00,000004,0.945150,0.945150,134.92,0.989126,0.989126

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000004,0.965278,0.965278,129.92,0.590829,0.590829
2021-05-27 09:30:00,000004,0.961700,0.961700,128.90,0.659256,0.659256
2021-05-28 09:30:00,000004,0.951797,0.951797,127.64,0.512597,0.512597
2021-05-31 09:30:00,000004,0.950193,0.950193,128.78,-0.400659,-0.400659
2021-06-01 09:30:00,000004,0.945472,0.945472,123.46,0.946847,0.946847

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000004,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000004,0.869898,0.869898,125.61,0.903449,0.903449
2021-05-27 09:30:00,000004,0.899991,0.899991,125.37,0.310894,0.310894
2021-05-28 09:30:00,000004,0.908936,0.908936,123.38,0.793369,0.793369
2021-05-31 09:30:00,000004,0.895139,0.895139,122.85,0.872090,0.872090
2021-06-01 09:30:00,000004,0.874703,0.874703,122.89,0.758900,0.758900

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000004,0.815852,0.815852,184.01,-0.086929,-0.086929
2020-01-03 09:30:00,000004,0.757146,0.757146,182.80,-0.066652,-0.066652
2020-01-06 09:30:00,000004,0.709466,0.709466,181.49,0.592432,0.592432
2020-01-07 09:30:00,000004,0.714717,0.714717,178.61,0.834185,0.834185
2020-01-08 09:30:00,000004,0.724340,0.724340,178.40,0.823147,0.823147
...,...,...,...,...,...,...
2021-05-26 09:30:00,000004,0.593782,0.593782,125.70,0.968447,0.968447
2021-05-27 09:30:00,000004,0.940623,0.940623,128.90,0.916397,0.916397
2021-05-28 09:30:00,000004,0.968057,0.968057,130.16,0.708135,0.708135
2021-05-31 09:30:00,000004,0.967819,0.967819,128.42,0.414041,0.414041
2021-06-01 09:30:00,000004,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000005,0.833746,0.833746,42.17,0.881679,0.881679
2021-05-27 09:30:00,000005,0.782485,0.782485,41.89,0.884685,0.884685
2021-05-28 09:30:00,000005,0.815323,0.815323,42.54,0.853641,0.853641
2021-05-31 09:30:00,000005,0.781410,0.781410,43.01,0.952784,0.952784
2021-06-01 09:30:00,000005,0.806255,0.806255,43.28,0.951111,0.951111

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000005,0.767504,0.767504,42.64,0.828362,0.828362
2021-05-27 09:30:00,000005,0.808509,0.808509,42.81,-0.416255,-0.416255
2021-05-28 09:30:00,000005,0.855932,0.855932,42.54,-0.545955,-0.545955
2021-05-31 09:30:00,000005,0.878398,0.878398,42.26,0.649224,0.649224
2021-06-01 09:30:00,000005,0.859715,0.859715,41.61,0.954961,0.954961

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000005,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000005,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000005,0.815519,0.815519,57.28,0.656316,0.656316
2020-01-03 09:30:00,000005,0.806546,0.806546,57.92,0.959983,0.959983
2020-01-06 09:30:00,000005,0.781329,0.781329,58.29,0.958735,0.958735
2020-01-07 09:30:00,000005,0.795255,0.795255,58.10,0.758695,0.758695
2020-01-08 09:30:00,000005,0.944355,0.944355,58.95,0.936155,0.936155
...,...,...,...,...,...,...
2021-05-26 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000005,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000005,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000006,0.836875,0.836875,388.80,0.199222,0.199222
2021-05-27 09:30:00,000006,0.838379,0.838379,387.71,0.276868,0.276868
2021-05-28 09:30:00,000006,0.793108,0.793108,391.36,0.913134,0.913134
2021-05-31 09:30:00,000006,0.767647,0.767647,397.20,0.988116,0.988116
2021-06-01 09:30:00,000006,0.865634,0.865634,402.67,0.845229,0.845229

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000006,0.954470,0.954470,404.86,0.659061,0.659061
2021-05-27 09:30:00,000006,0.908212,0.908212,397.56,0.967449,0.967449
2021-05-28 09:30:00,000006,0.889844,0.889844,391.35,0.932603,0.932603
2021-05-31 09:30:00,000006,0.906557,0.906557,386.97,0.968036,0.968036
2021-06-01 09:30:00,000006,0.906557,0.906557,386.25,0.939675,0.939675

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000006,0.929978,0.929978,395.74,0.991757,0.991757
2021-05-27 09:30:00,000006,0.928974,0.928974,395.37,0.885400,0.885400
2021-05-28 09:30:00,000006,0.914236,0.914236,392.45,0.939387,0.939387
2021-05-31 09:30:00,000006,0.864527,0.864527,393.91,0.358188,0.358188
2021-06-01 09:30:00,000006,0.935250,0.935250,393.91,-0.395170,-0.395170

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000006,0.842319,0.842319,395.74,0.721756,0.721756
2021-05-27 09:30:00,000006,0.712692,0.712692,393.91,0.718993,0.718993
2021-05-28 09:30:00,000006,0.627677,0.627677,393.18,0.904611,0.904611
2021-05-31 09:30:00,000006,0.643993,0.643993,388.80,0.989006,0.989006
2021-06-01 09:30:00,000006,0.727461,0.727461,386.61,0.958881,0.958881

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000006,0.846951,0.846951,379.05,0.967827,0.967827
2020-01-03 09:30:00,000006,0.867675,0.867675,383.66,0.989667,0.989667
2020-01-06 09:30:00,000006,0.868054,0.868054,385.43,0.913634,0.913634
2020-01-07 09:30:00,000006,0.898377,0.898377,386.50,0.774698,0.774698
2020-01-08 09:30:00,000006,0.963456,0.963456,387.92,0.812001,0.812001
...,...,...,...,...,...,...
2021-05-26 09:30:00,000006,0.869064,0.869064,382.96,0.889768,0.889768
2021-05-27 09:30:00,000006,0.872376,0.872376,385.15,0.934112,0.934112
2021-05-28 09:30:00,000006,0.879064,0.879064,387.34,0.784392,0.784392
2021-05-31 09:30:00,000006,0.898786,0.898786,386.97,0.793985,0.793985
2021-06-01 09:30:00,000006,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000007,0.861653,0.861653,62.96,0.917174,0.917174
2021-05-27 09:30:00,000007,0.899366,0.899366,62.38,0.796412,0.796412
2021-05-28 09:30:00,000007,0.776214,0.776214,61.72,0.840290,0.840290
2021-05-31 09:30:00,000007,0.812327,0.812327,62.54,0.374435,0.374435
2021-06-01 09:30:00,000007,0.813583,0.813583,65.60,0.965278,0.965278

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000007,0.848310,0.848310,63.20,0.870422,0.870422
2021-05-27 09:30:00,000007,0.856287,0.856287,62.13,0.955224,0.955224
2021-05-28 09:30:00,000007,0.851759,0.851759,63.03,0.950414,0.950414
2021-05-31 09:30:00,000007,0.815958,0.815958,62.79,0.698423,0.698423
2021-06-01 09:30:00,000007,0.846440,0.846440,63.37,-0.834239,-0.834239

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000007,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000007,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000007,0.859336,0.859336,159.21,0.304453,0.304453
2020-01-03 09:30:00,000007,0.854186,0.854186,158.30,0.599662,0.599662
2020-01-06 09:30:00,000007,0.756314,0.756314,157.97,0.336357,0.336357
2020-01-07 09:30:00,000007,0.699113,0.699113,156.89,0.535688,0.535688
2020-01-08 09:30:00,000007,0.646731,0.646731,156.89,0.556603,0.556603
...,...,...,...,...,...,...
2021-05-26 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000007,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000007,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000008,0.754588,0.754588,103.53,0.457009,0.457009
2021-05-27 09:30:00,000008,0.862703,0.862703,103.07,0.895768,0.895768
2021-05-28 09:30:00,000008,0.789744,0.789744,102.40,0.971748,0.971748
2021-05-31 09:30:00,000008,0.813088,0.813088,103.53,-0.137506,-0.137506
2021-06-01 09:30:00,000008,0.920633,0.920633,106.22,0.967856,0.967856

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000008,0.885780,0.885780,103.30,0.892871,0.892871
2021-05-27 09:30:00,000008,0.848716,0.848716,102.63,0.945055,0.945055
2021-05-28 09:30:00,000008,0.876038,0.876038,101.29,0.960946,0.960946
2021-05-31 09:30:00,000008,0.896466,0.896466,100.83,0.965136,0.965136
2021-06-01 09:30:00,000008,0.912164,0.912164,101.06,0.851600,0.851600

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000008,0.939908,0.939908,100.61,0.311421,0.311421
2021-05-27 09:30:00,000008,0.870690,0.870690,101.29,0.435313,0.435313
2021-05-28 09:30:00,000008,0.755814,0.755814,101.74,0.930868,0.930868
2021-05-31 09:30:00,000008,0.514534,0.514534,102.18,0.243269,0.243269
2021-06-01 09:30:00,000008,0.725744,0.725744,102.62,-0.380415,-0.380415

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000008,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000008,0.853871,0.853871,102.18,0.119301,0.119301
2021-05-27 09:30:00,000008,0.833274,0.833274,101.74,0.469174,0.469174
2021-05-28 09:30:00,000008,0.816451,0.816451,101.51,0.855114,0.855114
2021-05-31 09:30:00,000008,0.824826,0.824826,101.06,0.882859,0.882859
2021-06-01 09:30:00,000008,0.824826,0.824826,101.06,0.889880,0.889880

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000008,0.812260,0.812260,161.91,0.295036,0.295036
2020-01-03 09:30:00,000008,0.807231,0.807231,164.59,0.887772,0.887772
2020-01-06 09:30:00,000008,0.880817,0.880817,166.83,0.954982,0.954982
2020-01-07 09:30:00,000008,0.922985,0.922985,167.27,0.933477,0.933477
2020-01-08 09:30:00,000008,0.949084,0.949084,168.39,0.902798,0.902798
...,...,...,...,...,...,...
2021-05-26 09:30:00,000008,0.822721,0.822721,101.96,0.790181,0.790181
2021-05-27 09:30:00,000008,0.798826,0.798826,102.40,0.579760,0.579760
2021-05-28 09:30:00,000008,0.823613,0.823613,102.18,0.006226,0.006226
2021-05-31 09:30:00,000008,0.696559,0.696559,101.96,-0.061460,-0.061460
2021-06-01 09:30:00,000008,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000009,0.943461,0.943461,170.61,0.785130,0.785130
2021-05-27 09:30:00,000009,0.932598,0.932598,173.64,0.936163,0.936163
2021-05-28 09:30:00,000009,0.926874,0.926874,175.41,0.958742,0.958742
2021-05-31 09:30:00,000009,0.880419,0.880419,177.01,0.593118,0.593118
2021-06-01 09:30:00,000009,0.799677,0.799677,177.01,0.880118,0.880118

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000009,0.959526,0.959526,186.07,-0.098692,-0.098692
2021-05-27 09:30:00,000009,0.963037,0.963037,186.34,0.034684,0.034684
2021-05-28 09:30:00,000009,0.971672,0.971672,185.53,0.412093,0.412093
2021-05-31 09:30:00,000009,0.958595,0.958595,185.80,0.297004,0.297004
2021-06-01 09:30:00,000009,0.929714,0.929714,187.66,0.928101,0.928101

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000009,0.887703,0.887703,186.96,0.872892,0.872892
2021-05-27 09:30:00,000009,0.380937,0.380937,183.50,0.971638,0.971638
2021-05-28 09:30:00,000009,0.843013,0.843013,178.69,0.995914,0.995914
2021-05-31 09:30:00,000009,0.916562,0.916562,176.38,0.985380,0.985380
2021-06-01 09:30:00,000009,0.920423,0.920423,176.03,0.912216,0.912216

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000009,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000009,0.956479,0.956479,175.41,0.898427,0.898427
2021-05-27 09:30:00,000009,0.953552,0.953552,177.81,0.991995,0.991995
2021-05-28 09:30:00,000009,0.929899,0.929899,178.43,-0.611605,-0.611605
2021-05-31 09:30:00,000009,0.836580,0.836580,176.65,-0.513219,-0.513219
2021-06-01 09:30:00,000009,0.500586,0.500586,173.46,0.540936,0.540936

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000009,0.998127,0.998127,110.39,0.979921,0.979921
2020-01-03 09:30:00,000009,0.997338,0.997338,114.63,0.956404,0.956404
2020-01-06 09:30:00,000009,0.997216,0.997216,115.70,0.664632,0.664632
2020-01-07 09:30:00,000009,0.996829,0.996829,121.28,0.881016,0.881016
2020-01-08 09:30:00,000009,0.990900,0.990900,131.20,0.992115,0.992115
...,...,...,...,...,...,...
2021-05-26 09:30:00,000009,0.783109,0.783109,171.86,0.621144,0.621144
2021-05-27 09:30:00,000009,0.812867,0.812867,173.99,-0.465440,-0.465440
2021-05-28 09:30:00,000009,0.846970,0.846970,172.83,-0.568634,-0.568634
2021-05-31 09:30:00,000009,0.835016,0.835016,173.72,0.027040,0.027040
2021-06-01 09:30:00,000009,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000010,0.835674,0.835674,87.17,0.976745,0.976745
2021-05-27 09:30:00,000010,0.950574,0.950574,91.37,-0.259694,-0.259694
2021-05-28 09:30:00,000010,0.973700,0.973700,95.14,0.806535,0.806535
2021-05-31 09:30:00,000010,0.981590,0.981590,95.79,0.733308,0.733308
2021-06-01 09:30:00,000010,0.971289,0.971289,97.19,0.878650,0.878650

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000010,0.963654,0.963654,96.44,0.824126,0.824126
2021-05-27 09:30:00,000010,0.963259,0.963259,95.14,0.738788,0.738788
2021-05-28 09:30:00,000010,0.946719,0.946719,93.09,0.972169,0.972169
2021-05-31 09:30:00,000010,0.919665,0.919665,93.20,0.899162,0.899162
2021-06-01 09:30:00,000010,0.813584,0.813584,93.85,0.957647,0.957647

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000010,0.764120,0.764120,90.51,0.931533,0.931533
2021-05-27 09:30:00,000010,0.798540,0.798540,87.92,0.842164,0.842164
2021-05-28 09:30:00,000010,0.788777,0.788777,88.68,0.833115,0.833115
2021-05-31 09:30:00,000010,0.770450,0.770450,89.00,0.587445,0.587445
2021-06-01 09:30:00,000010,0.693838,0.693838,88.78,0.434948,0.434948

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000010,0.748719,0.748719,86.84,0.823329,0.823329
2021-05-27 09:30:00,000010,0.706415,0.706415,85.65,0.978291,0.978291
2021-05-28 09:30:00,000010,0.622024,0.622024,85.98,0.845639,0.845639
2021-05-31 09:30:00,000010,0.731109,0.731109,86.52,0.656275,0.656275
2021-06-01 09:30:00,000010,0.708192,0.708192,87.70,0.916901,0.916901

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000010,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000010,0.728832,0.728832,88.57,-0.025403,-0.025403
2021-05-27 09:30:00,000010,0.729201,0.729201,88.14,-0.026924,-0.026924
2021-05-28 09:30:00,000010,0.849892,0.849892,88.03,-0.184242,-0.184242
2021-05-31 09:30:00,000010,0.849764,0.849764,87.27,0.779693,0.779693
2021-06-01 09:30:00,000010,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000011,0.855884,0.855884,93.77,0.920537,0.920537
2021-05-27 09:30:00,000011,0.887656,0.887656,94.48,0.735334,0.735334
2021-05-28 09:30:00,000011,0.886563,0.886563,96.62,0.753670,0.753670
2021-05-31 09:30:00,000011,0.875560,0.875560,98.05,0.925670,0.925670
2021-06-01 09:30:00,000011,0.863578,0.863578,97.41,0.474068,0.474068

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000011,0.828403,0.828403,100.98,0.220124,0.220124
2021-05-27 09:30:00,000011,0.792668,0.792668,99.78,0.440376,0.440376
2021-05-28 09:30:00,000011,0.892770,0.892770,98.42,0.441264,0.441264
2021-05-31 09:30:00,000011,0.816059,0.816059,97.11,0.960101,0.960101
2021-06-01 09:30:00,000011,0.724873,0.724873,96.17,0.841092,0.841092

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000011,0.859765,0.859765,93.75,-0.698252,-0.698252
2021-05-27 09:30:00,000011,0.883302,0.883302,94.02,-0.653680,-0.653680
2021-05-28 09:30:00,000011,0.901542,0.901542,92.51,0.411109,0.411109
2021-05-31 09:30:00,000011,0.921992,0.921992,92.51,0.199711,0.199711
2021-06-01 09:30:00,000011,0.913278,0.913278,92.56,-0.338718,-0.338718

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000011,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000011,0.939476,0.939476,96.65,-0.001481,-0.001481
2021-05-27 09:30:00,000011,0.931366,0.931366,96.77,-0.005539,-0.005539
2021-05-28 09:30:00,000011,0.944219,0.944219,96.42,-0.516577,-0.516577
2021-05-31 09:30:00,000011,0.912419,0.912419,93.79,0.845060,0.845060
2021-06-01 09:30:00,000011,0.905812,0.905812,92.32,0.720457,0.720457

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000011,0.807263,0.807263,67.78,-0.339358,-0.339358
2020-01-03 09:30:00,000011,0.823198,0.823198,68.47,0.837077,0.837077
2020-01-06 09:30:00,000011,0.860825,0.860825,68.47,0.789564,0.789564
2020-01-07 09:30:00,000011,0.873885,0.873885,67.71,0.878612,0.878612
2020-01-08 09:30:00,000011,0.962589,0.962589,68.25,0.743052,0.743052
...,...,...,...,...,...,...
2021-05-26 09:30:00,000011,0.915631,0.915631,93.87,0.525080,0.525080
2021-05-27 09:30:00,000011,0.890584,0.890584,96.51,0.969843,0.969843
2021-05-28 09:30:00,000011,0.908089,0.908089,100.03,0.994865,0.994865
2021-05-31 09:30:00,000011,0.948835,0.948835,100.57,0.791553,0.791553
2021-06-01 09:30:00,000011,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000012,0.988061,0.988061,376.50,0.829472,0.829472
2021-05-27 09:30:00,000012,0.985942,0.985942,373.56,0.911738,0.911738
2021-05-28 09:30:00,000012,0.985879,0.985879,385.60,0.985777,0.985777
2021-05-31 09:30:00,000012,0.975554,0.975554,396.32,0.954116,0.954116
2021-06-01 09:30:00,000012,0.963920,0.963920,412.12,0.933501,0.933501

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000012,0.985385,0.985385,435.42,0.935095,0.935095
2021-05-27 09:30:00,000012,0.985880,0.985880,439.97,0.563893,0.563893
2021-05-28 09:30:00,000012,0.990630,0.990630,450.41,0.723940,0.723940
2021-05-31 09:30:00,000012,0.992031,0.992031,457.91,0.558435,0.558435
2021-06-01 09:30:00,000012,0.989779,0.989779,468.08,0.720006,0.720006

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000012,0.987984,0.987984,487.37,0.872221,0.872221
2021-05-27 09:30:00,000012,0.970419,0.970419,485.23,0.182346,0.182346
2021-05-28 09:30:00,000012,0.955944,0.955944,481.48,-0.376795,-0.376795
2021-05-31 09:30:00,000012,0.915016,0.915016,484.96,0.252282,0.252282
2021-06-01 09:30:00,000012,0.872295,0.872295,486.30,0.906513,0.906513

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000012,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000012,-0.184076,-0.184076,480.13,0.872613,0.872613
2021-05-27 09:30:00,000012,-0.226660,-0.226660,479.60,0.920467,0.920467
2021-05-28 09:30:00,000012,-0.270688,-0.270688,505.84,0.974862,0.974862
2021-05-31 09:30:00,000012,0.117978,0.117978,500.49,0.977412,0.977412
2021-06-01 09:30:00,000012,0.445086,0.445086,461.66,0.981457,0.981457

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000012,0.887746,0.887746,264.05,0.052220,0.052220
2020-01-03 09:30:00,000012,0.920081,0.920081,265.37,0.257303,0.257303
2020-01-06 09:30:00,000012,0.934600,0.934600,266.17,0.274452,0.274452
2020-01-07 09:30:00,000012,0.930139,0.930139,261.41,0.677393,0.677393
2020-01-08 09:30:00,000012,0.938623,0.938623,264.85,0.889796,0.889796
...,...,...,...,...,...,...
2021-05-26 09:30:00,000012,0.642629,0.642629,482.28,0.629308,0.629308
2021-05-27 09:30:00,000012,0.646637,0.646637,502.63,0.917265,0.917265
2021-05-28 09:30:00,000012,0.802581,0.802581,532.35,0.969711,0.969711
2021-05-31 09:30:00,000012,0.884118,0.884118,544.94,0.942766,0.942766
2021-06-01 09:30:00,000012,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000014,0.873049,0.873049,85.42,0.969234,0.969234
2021-05-27 09:30:00,000014,0.928874,0.928874,84.98,0.958926,0.958926
2021-05-28 09:30:00,000014,0.933277,0.933277,85.25,0.960510,0.960510
2021-05-31 09:30:00,000014,0.946830,0.946830,85.96,0.828240,0.828240
2021-06-01 09:30:00,000014,0.945256,0.945256,86.61,0.960058,0.960058

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000014,0.967724,0.967724,89.59,0.924991,0.924991
2021-05-27 09:30:00,000014,0.978425,0.978425,90.74,0.922579,0.922579
2021-05-28 09:30:00,000014,0.995186,0.995186,91.44,0.978566,0.978566
2021-05-31 09:30:00,000014,0.789854,0.789854,88.67,0.843377,0.843377
2021-06-01 09:30:00,000014,0.772089,0.772089,84.82,0.961732,0.961732

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000014,0.857364,0.857364,83.73,0.885394,0.885394
2021-05-27 09:30:00,000014,0.887571,0.887571,83.40,0.961106,0.961106
2021-05-28 09:30:00,000014,0.898121,0.898121,83.51,0.304915,0.304915
2021-05-31 09:30:00,000014,0.889215,0.889215,83.90,0.382874,0.382874
2021-06-01 09:30:00,000014,0.874730,0.874730,84.76,0.909796,0.909796

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000014,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000014,0.871610,0.871610,84.77,0.772510,0.772510
2021-05-27 09:30:00,000014,0.887257,0.887257,84.17,0.935739,0.935739
2021-05-28 09:30:00,000014,0.916861,0.916861,83.90,0.665640,0.665640
2021-05-31 09:30:00,000014,0.946106,0.946106,83.62,0.755043,0.755043
2021-06-01 09:30:00,000014,0.923085,0.923085,83.68,0.659677,0.659677

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000014,0.768821,0.768821,100.72,0.692239,0.692239
2020-01-03 09:30:00,000014,0.770308,0.770308,101.92,0.965707,0.965707
2020-01-06 09:30:00,000014,0.678857,0.678857,102.08,0.962064,0.962064
2020-01-07 09:30:00,000014,0.504832,0.504832,101.37,0.279209,0.279209
2020-01-08 09:30:00,000014,0.726030,0.726030,104.79,0.702014,0.702014
...,...,...,...,...,...,...
2021-05-26 09:30:00,000014,0.839713,0.839713,84.44,0.785675,0.785675
2021-05-27 09:30:00,000014,0.857624,0.857624,85.10,0.923512,0.923512
2021-05-28 09:30:00,000014,0.877325,0.877325,85.52,0.940846,0.940846
2021-05-31 09:30:00,000014,0.818883,0.818883,85.80,0.976890,0.976890
2021-06-01 09:30:00,000014,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000016,0.939347,0.939347,264.72,0.949521,0.949521
2021-05-27 09:30:00,000016,0.930640,0.930640,265.59,0.927720,0.927720
2021-05-28 09:30:00,000016,0.947320,0.947320,265.81,0.600829,0.600829
2021-05-31 09:30:00,000016,0.956615,0.956615,267.99,0.976749,0.976749
2021-06-01 09:30:00,000016,0.965842,0.965842,271.05,0.944663,0.944663

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000016,0.869236,0.869236,269.95,0.441726,0.441726
2021-05-27 09:30:00,000016,0.912689,0.912689,273.88,0.852258,0.852258
2021-05-28 09:30:00,000016,0.952660,0.952660,272.57,0.908459,0.908459
2021-05-31 09:30:00,000016,0.944217,0.944217,271.48,0.952458,0.952458
2021-06-01 09:30:00,000016,0.913657,0.913657,273.01,0.620260,0.620260

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000016,0.973299,0.973299,281.52,0.219702,0.219702
2021-05-27 09:30:00,000016,0.961217,0.961217,278.68,0.311014,0.311014
2021-05-28 09:30:00,000016,0.955593,0.955593,282.83,-0.540873,-0.540873
2021-05-31 09:30:00,000016,0.976753,0.976753,292.21,0.679344,0.679344
2021-06-01 09:30:00,000016,0.967276,0.967276,289.59,0.100430,0.100430

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000016,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000016,0.961251,0.961251,289.38,0.784600,0.784600
2021-05-27 09:30:00,000016,0.955081,0.955081,287.19,0.889063,0.889063
2021-05-28 09:30:00,000016,0.924260,0.924260,283.48,0.961487,0.961487
2021-05-31 09:30:00,000016,0.912694,0.912694,281.08,0.898181,0.898181
2021-06-01 09:30:00,000016,0.919417,0.919417,280.00,0.886062,0.886062

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000016,0.882581,0.882581,189.96,0.977604,0.977604
2020-01-03 09:30:00,000016,0.883419,0.883419,192.12,0.996836,0.996836
2020-01-06 09:30:00,000016,0.767109,0.767109,193.64,0.852951,0.852951
2020-01-07 09:30:00,000016,0.661237,0.661237,191.91,0.940419,0.940419
2020-01-08 09:30:00,000016,0.614927,0.614927,193.43,0.966621,0.966621
...,...,...,...,...,...,...
2021-05-26 09:30:00,000016,0.902539,0.902539,281.52,0.255953,0.255953
2021-05-27 09:30:00,000016,0.905506,0.905506,281.52,0.699211,0.699211
2021-05-28 09:30:00,000016,0.918543,0.918543,283.93,0.131529,0.131529
2021-05-31 09:30:00,000016,0.918006,0.918006,286.11,0.819173,0.819173
2021-06-01 09:30:00,000016,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000017,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000017,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000017,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000017,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000017,0.741401,0.741401,24.15,0.742264,0.742264
2020-01-03 09:30:00,000017,0.732131,0.732131,24.44,0.890653,0.890653
2020-01-06 09:30:00,000017,0.713917,0.713917,24.65,0.950661,0.950661
2020-01-07 09:30:00,000017,0.733034,0.733034,24.60,0.505366,0.505366
2020-01-08 09:30:00,000017,0.811798,0.811798,24.95,0.924537,0.924537
...,...,...,...,...,...,...
2021-05-26 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-27 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-28 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-05-31 09:30:00,000017,NaN,NaN,NaN,NaN,NaN
2021-06-01 09:30:00,000017,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000018,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000018,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000018,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000018,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000018,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000018,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000019,0.829868,0.829868,59.09,0.824871,0.824871
2021-05-27 09:30:00,000019,0.874382,0.874382,58.66,0.715586,0.715586
2021-05-28 09:30:00,000019,0.853836,0.853836,59.30,0.657622,0.657622
2021-05-31 09:30:00,000019,0.749912,0.749912,59.80,0.883253,0.883253
2021-06-01 09:30:00,000019,0.800428,0.800428,60.61,0.954611,0.954611

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000019,0.782556,0.782556,60.23,0.900791,0.900791
2021-05-27 09:30:00,000019,0.761195,0.761195,59.81,0.954526,0.954526
2021-05-28 09:30:00,000019,0.693432,0.693432,59.63,0.507088,0.507088
2021-05-31 09:30:00,000019,0.837166,0.837166,59.93,0.791288,0.791288
2021-06-01 09:30:00,000019,0.683179,0.683179,59.42,0.914254,0.914254

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000019,0.764826,0.764826,59.42,0.207913,0.207913
2021-05-27 09:30:00,000019,0.771704,0.771704,60.56,0.328897,0.328897
2021-05-28 09:30:00,000019,0.794357,0.794357,60.73,0.510387,0.510387
2021-05-31 09:30:00,000019,0.828991,0.828991,61.66,0.914732,0.914732
2021-06-01 09:30:00,000019,0.928675,0.928675,62.88,0.958491,0.958491

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000019,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000019,0.978034,0.978034,62.21,0.208222,0.208222
2021-05-27 09:30:00,000019,0.981336,0.981336,62.59,-0.039035,-0.039035
2021-05-28 09:30:00,000019,0.983308,0.983308,61.70,0.587959,0.587959
2021-05-31 09:30:00,000019,0.968748,0.968748,61.44,0.879971,0.879971
2021-06-01 09:30:00,000019,0.961925,0.961925,62.33,0.943236,0.943236

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000019,0.785365,0.785365,50.06,0.744585,0.744585
2020-01-03 09:30:00,000019,0.838609,0.838609,50.47,0.862977,0.862977
2020-01-06 09:30:00,000019,0.931498,0.931498,51.54,0.956580,0.956580
2020-01-07 09:30:00,000019,0.969171,0.969171,51.94,0.904300,0.904300
2020-01-08 09:30:00,000019,0.979022,0.979022,52.32,0.769524,0.769524
...,...,...,...,...,...,...
2021-05-26 09:30:00,000019,0.909925,0.909925,61.74,0.945679,0.945679
2021-05-27 09:30:00,000019,0.922088,0.922088,63.97,0.225929,0.225929
2021-05-28 09:30:00,000019,0.994480,0.994480,68.52,0.950049,0.950049
2021-05-31 09:30:00,000019,0.971913,0.971913,66.46,0.936539,0.936539
2021-06-01 09:30:00,000019,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000020,0.888476,0.888476,31.72,0.867845,0.867845
2021-05-27 09:30:00,000020,0.785558,0.785558,32.03,0.789742,0.789742
2021-05-28 09:30:00,000020,0.788511,0.788511,32.01,-0.295083,-0.295083
2021-05-31 09:30:00,000020,0.727985,0.727985,32.18,0.380009,0.380009
2021-06-01 09:30:00,000020,0.758402,0.758402,32.70,0.959764,0.959764

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000020,0.813062,0.813062,32.84,0.894497,0.894497
2021-05-27 09:30:00,000020,0.661823,0.661823,32.77,0.583191,0.583191
2021-05-28 09:30:00,000020,0.708165,0.708165,32.26,0.247294,0.247294
2021-05-31 09:30:00,000020,0.585812,0.585812,32.34,0.574185,0.574185
2021-06-01 09:30:00,000020,0.375096,0.375096,32.33,-0.308354,-0.308354

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000020,0.589442,0.589442,31.64,0.791347,0.791347
2021-05-27 09:30:00,000020,0.667283,0.667283,31.53,0.772304,0.772304
2021-05-28 09:30:00,000020,0.786758,0.786758,31.50,-0.562698,-0.562698
2021-05-31 09:30:00,000020,0.755667,0.755667,31.74,-0.830287,-0.830287
2021-06-01 09:30:00,000020,0.710965,0.710965,31.92,-0.065668,-0.065668

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000020,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000020,0.633901,0.633901,31.75,-0.559143,-0.559143
2021-05-27 09:30:00,000020,0.639090,0.639090,31.78,-0.463162,-0.463162
2021-05-28 09:30:00,000020,0.875597,0.875597,31.64,-0.238432,-0.238432
2021-05-31 09:30:00,000020,0.906832,0.906832,31.25,0.983481,0.983481
2021-06-01 09:30:00,000020,0.915391,0.915391,31.30,0.952417,0.952417

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000020,0.513625,0.513625,37.33,0.870845,0.870845
2020-01-03 09:30:00,000020,0.480688,0.480688,37.82,0.966723,0.966723
2020-01-06 09:30:00,000020,0.636317,0.636317,38.43,0.968661,0.968661
2020-01-07 09:30:00,000020,0.671544,0.671544,38.49,0.851472,0.851472
2020-01-08 09:30:00,000020,0.938621,0.938621,38.77,0.504656,0.504656
...,...,...,...,...,...,...
2021-05-26 09:30:00,000020,0.897416,0.897416,31.69,0.962147,0.962147
2021-05-27 09:30:00,000020,0.900219,0.900219,31.90,0.847796,0.847796
2021-05-28 09:30:00,000020,0.932506,0.932506,31.89,0.874425,0.874425
2021-05-31 09:30:00,000020,0.934169,0.934169,31.87,0.882077,0.882077
2021-06-01 09:30:00,000020,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000021,0.902210,0.902210,541.08,0.724827,0.724827
2021-05-27 09:30:00,000021,0.901591,0.901591,542.34,0.317826,0.317826
2021-05-28 09:30:00,000021,0.776544,0.776544,535.05,0.224660,0.224660
2021-05-31 09:30:00,000021,0.878665,0.878665,522.55,0.810521,0.810521
2021-06-01 09:30:00,000021,0.914335,0.914335,522.69,0.829114,0.829114

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000021,0.860371,0.860371,523.53,0.538741,0.538741
2021-05-27 09:30:00,000021,0.834211,0.834211,523.39,0.838465,0.838465
2021-05-28 09:30:00,000021,0.784202,0.784202,523.68,0.690442,0.690442
2021-05-31 09:30:00,000021,0.617916,0.617916,521.28,0.283091,0.283091
2021-06-01 09:30:00,000021,0.558053,0.558053,510.76,0.859644,0.859644

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000021,0.893749,0.893749,480.85,0.741756,0.741756
2021-05-27 09:30:00,000021,0.907215,0.907215,473.69,0.777139,0.777139
2021-05-28 09:30:00,000021,0.929513,0.929513,464.98,0.841197,0.841197
2021-05-31 09:30:00,000021,0.938857,0.938857,464.00,0.439140,0.439140
2021-06-01 09:30:00,000021,0.930007,0.930007,474.12,0.527717,0.527717

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000021,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000021,0.839997,0.839997,483.24,0.944806,0.944806
2021-05-27 09:30:00,000021,0.702609,0.702609,485.20,0.576665,0.576665
2021-05-28 09:30:00,000021,0.888158,0.888158,493.90,0.836361,0.836361
2021-05-31 09:30:00,000021,0.899839,0.899839,489.55,0.878753,0.878753
2021-06-01 09:30:00,000021,0.901155,0.901155,485.35,0.807265,0.807265

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000021,0.953468,0.953468,345.86,0.573496,0.573496
2020-01-03 09:30:00,000021,0.959246,0.959246,353.98,0.713236,0.713236
2020-01-06 09:30:00,000021,0.972791,0.972791,380.44,0.989210,0.989210
2020-01-07 09:30:00,000021,0.981971,0.981971,407.88,0.998219,0.998219
2020-01-08 09:30:00,000021,0.990639,0.990639,412.64,0.768071,0.768071
...,...,...,...,...,...,...
2021-05-26 09:30:00,000021,0.894331,0.894331,494.19,0.982232,0.982232
2021-05-27 09:30:00,000021,0.905594,0.905594,495.45,0.734420,0.734420
2021-05-28 09:30:00,000021,0.843327,0.843327,502.47,0.428391,0.428391
2021-05-31 09:30:00,000021,0.890900,0.890900,507.81,0.513418,0.513418
2021-06-01 09:30:00,000021,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000023,0.822384,0.822384,84.19,0.989118,0.989118
2021-05-27 09:30:00,000023,0.887093,0.887093,83.60,0.905406,0.905406
2021-05-28 09:30:00,000023,0.910803,0.910803,84.60,0.785037,0.785037
2021-05-31 09:30:00,000023,0.886242,0.886242,85.58,0.946152,0.946152
2021-06-01 09:30:00,000023,0.838165,0.838165,86.27,0.914844,0.914844

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000023,0.811966,0.811966,86.16,0.539976,0.539976
2021-05-27 09:30:00,000023,0.769336,0.769336,85.36,0.716797,0.716797
2021-05-28 09:30:00,000023,0.782415,0.782415,84.44,0.830891,0.830891
2021-05-31 09:30:00,000023,0.927842,0.927842,83.20,0.927909,0.927909
2021-06-01 09:30:00,000023,0.921925,0.921925,83.06,0.870079,0.870079

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000023,0.942712,0.942712,85.04,0.789481,0.789481
2021-05-27 09:30:00,000023,0.759394,0.759394,86.73,0.513707,0.513707
2021-05-28 09:30:00,000023,0.742959,0.742959,85.71,0.220977,0.220977
2021-05-31 09:30:00,000023,0.685180,0.685180,86.91,0.749675,0.749675
2021-06-01 09:30:00,000023,0.752075,0.752075,86.83,0.338287,0.338287

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000023,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000023,0.255901,0.255901,86.14,0.304781,0.304781
2021-05-27 09:30:00,000023,0.106503,0.106503,84.70,-0.447866,-0.447866
2021-05-28 09:30:00,000023,0.184240,0.184240,83.34,-0.201901,-0.201901
2021-05-31 09:30:00,000023,0.244067,0.244067,83.74,-0.178219,-0.178219
2021-06-01 09:30:00,000023,0.316598,0.316598,83.44,-0.206223,-0.206223

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000023,0.624052,0.624052,68.92,0.935616,0.935616
2020-01-03 09:30:00,000023,0.753298,0.753298,70.07,0.954677,0.954677
2020-01-06 09:30:00,000023,0.854688,0.854688,70.70,0.969269,0.969269
2020-01-07 09:30:00,000023,0.869249,0.869249,70.71,0.822468,0.822468
2020-01-08 09:30:00,000023,0.929367,0.929367,71.32,0.951820,0.951820
...,...,...,...,...,...,...
2021-05-26 09:30:00,000023,0.446607,0.446607,81.82,0.777968,0.777968
2021-05-27 09:30:00,000023,0.394941,0.394941,81.52,0.805068,0.805068
2021-05-28 09:30:00,000023,0.317605,0.317605,81.84,0.734662,0.734662
2021-05-31 09:30:00,000023,-0.065748,-0.065748,82.05,0.570133,0.570133
2021-06-01 09:30:00,000023,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000025,0.731758,0.731758,80.65,0.981123,0.981123
2021-05-27 09:30:00,000025,0.384327,0.384327,81.53,0.993288,0.993288
2021-05-28 09:30:00,000025,0.659235,0.659235,81.66,0.144133,0.144133
2021-05-31 09:30:00,000025,0.624188,0.624188,82.54,-0.505548,-0.505548
2021-06-01 09:30:00,000025,0.709427,0.709427,83.39,0.232369,0.232369

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000025,0.755864,0.755864,81.91,0.809347,0.809347
2021-05-27 09:30:00,000025,0.764752,0.764752,81.39,0.910814,0.910814
2021-05-28 09:30:00,000025,0.764752,0.764752,81.04,0.558797,0.558797
2021-05-31 09:30:00,000025,0.712832,0.712832,80.54,0.612274,0.612274
2021-06-01 09:30:00,000025,0.792978,0.792978,79.99,0.269580,0.269580

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000025,0.833032,0.833032,79.01,0.851293,0.851293
2021-05-27 09:30:00,000025,0.772089,0.772089,79.34,0.326692,0.326692
2021-05-28 09:30:00,000025,0.766832,0.766832,78.87,0.759852,0.759852
2021-05-31 09:30:00,000025,0.708153,0.708153,78.88,0.709531,0.709531
2021-06-01 09:30:00,000025,0.622935,0.622935,79.73,0.941926,0.941926

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000025,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000025,0.558995,0.558995,80.10,0.245710,0.245710
2021-05-27 09:30:00,000025,0.560935,0.560935,79.64,0.792427,0.792427
2021-05-28 09:30:00,000025,0.822049,0.822049,79.39,0.809995,0.809995
2021-05-31 09:30:00,000025,0.786102,0.786102,79.09,0.821779,0.821779
2021-06-01 09:30:00,000025,0.784921,0.784921,78.93,0.782125,0.782125

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000025,0.668847,0.668847,114.96,0.915831,0.915831
2020-01-03 09:30:00,000025,0.720699,0.720699,116.16,0.543213,0.543213
2020-01-06 09:30:00,000025,0.766645,0.766645,115.72,0.321776,0.321776
2020-01-07 09:30:00,000025,0.749967,0.749967,115.20,0.626549,0.626549
2020-01-08 09:30:00,000025,0.791826,0.791826,116.11,0.740390,0.740390
...,...,...,...,...,...,...
2021-05-26 09:30:00,000025,0.740825,0.740825,80.05,0.883230,0.883230
2021-05-27 09:30:00,000025,0.754535,0.754535,80.46,0.983825,0.983825
2021-05-28 09:30:00,000025,0.824727,0.824727,80.81,0.956683,0.956683
2021-05-31 09:30:00,000025,0.807139,0.807139,80.49,0.581140,0.581140
2021-06-01 09:30:00,000025,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000026,0.573758,0.573758,229.31,0.612119,0.612119
2021-05-27 09:30:00,000026,0.710804,0.710804,229.16,0.697015,0.697015
2021-05-28 09:30:00,000026,0.711226,0.711226,238.53,0.652168,0.652168
2021-05-31 09:30:00,000026,0.651669,0.651669,243.34,0.642432,0.642432
2021-06-01 09:30:00,000026,0.635600,0.635600,248.83,0.752174,0.752174

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000026,0.819199,0.819199,258.90,0.837675,0.837675
2021-05-27 09:30:00,000026,0.849343,0.849343,256.35,0.637484,0.637484
2021-05-28 09:30:00,000026,0.955155,0.955155,253.64,0.772360,0.772360
2021-05-31 09:30:00,000026,0.976508,0.976508,248.53,0.826278,0.826278
2021-06-01 09:30:00,000026,0.931487,0.931487,254.25,0.705511,0.705511

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000026,0.734271,0.734271,255.41,0.696960,0.696960
2021-05-27 09:30:00,000026,0.698217,0.698217,254.33,0.931101,0.931101
2021-05-28 09:30:00,000026,0.697725,0.697725,252.47,0.987325,0.987325
2021-05-31 09:30:00,000026,0.631861,0.631861,247.74,0.941072,0.941072
2021-06-01 09:30:00,000026,0.672860,0.672860,251.00,0.480142,0.480142

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000026,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000026,0.743879,0.743879,243.87,0.550655,0.550655
2021-05-27 09:30:00,000026,0.753245,0.753245,239.92,0.600608,0.600608
2021-05-28 09:30:00,000026,0.836506,0.836506,236.05,0.933009,0.933009
2021-05-31 09:30:00,000026,0.896769,0.896769,230.40,0.980120,0.980120
2021-06-01 09:30:00,000026,0.912480,0.912480,230.09,0.975262,0.975262

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000026,0.961659,0.961659,166.03,0.884672,0.884672
2020-01-03 09:30:00,000026,0.959999,0.959999,170.88,0.934115,0.934115
2020-01-06 09:30:00,000026,0.958468,0.958468,170.27,0.873125,0.873125
2020-01-07 09:30:00,000026,0.950778,0.950778,171.64,0.664865,0.664865
2020-01-08 09:30:00,000026,0.825339,0.825339,173.22,0.900304,0.900304
...,...,...,...,...,...,...
2021-05-26 09:30:00,000026,0.926975,0.926975,231.17,0.445788,0.445788
2021-05-27 09:30:00,000026,0.945381,0.945381,232.10,0.470951,0.470951
2021-05-28 09:30:00,000026,0.925134,0.925134,230.24,0.730460,0.730460
2021-05-31 09:30:00,000026,0.870758,0.870758,229.70,0.326357,0.326357
2021-06-01 09:30:00,000026,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000027,0.857569,0.857569,334.69,0.834358,0.834358
2021-05-27 09:30:00,000027,0.859979,0.859979,319.27,0.921105,0.921105
2021-05-28 09:30:00,000027,0.717896,0.717896,317.30,0.863609,0.863609
2021-05-31 09:30:00,000027,0.752545,0.752545,308.12,0.719537,0.719537
2021-06-01 09:30:00,000027,0.769027,0.769027,310.25,0.560963,0.560963

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000027,0.881043,0.881043,299.27,0.861326,0.861326
2021-05-27 09:30:00,000027,0.878027,0.878027,300.58,0.131800,0.131800
2021-05-28 09:30:00,000027,0.872600,0.872600,292.22,0.763158,0.763158
2021-05-31 09:30:00,000027,0.770997,0.770997,288.45,0.934272,0.934272
2021-06-01 09:30:00,000027,0.811633,0.811633,283.85,0.889037,0.889037

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000027,0.917056,0.917056,284.84,0.924615,0.924615
2021-05-27 09:30:00,000027,0.896489,0.896489,287.30,-0.115527,-0.115527
2021-05-28 09:30:00,000027,0.852151,0.852151,299.92,0.790302,0.790302
2021-05-31 09:30:00,000027,0.934327,0.934327,320.09,0.968823,0.968823
2021-06-01 09:30:00,000027,0.968889,0.968889,317.96,0.405903,0.405903

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000027,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000027,0.987878,0.987878,323.21,0.048834,0.048834
2021-05-27 09:30:00,000027,0.976130,0.976130,332.56,-0.749688,-0.749688
2021-05-28 09:30:00,000027,0.979106,0.979106,354.53,0.846674,0.846674
2021-05-31 09:30:00,000027,0.960110,0.960110,366.01,0.949927,0.949927
2021-06-01 09:30:00,000027,0.956930,0.956930,358.47,0.703349,0.703349

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000027,0.880624,0.880624,167.71,0.677823,0.677823
2020-01-03 09:30:00,000027,0.887335,0.887335,169.07,0.932100,0.932100
2020-01-06 09:30:00,000027,0.898982,0.898982,169.21,0.932421,0.932421
2020-01-07 09:30:00,000027,0.888442,0.888442,168.94,0.903407,0.903407
2020-01-08 09:30:00,000027,0.978047,0.978047,169.88,0.709474,0.709474
...,...,...,...,...,...,...
2021-05-26 09:30:00,000027,0.949856,0.949856,343.38,0.942494,0.942494
2021-05-27 09:30:00,000027,0.945574,0.945574,350.60,0.416591,0.416591
2021-05-28 09:30:00,000027,0.906668,0.906668,354.86,0.672852,0.672852
2021-05-31 09:30:00,000027,0.882943,0.882943,356.17,0.479412,0.479412
2021-06-01 09:30:00,000027,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000028,0.911876,0.911876,333.32,0.912148,0.912148
2021-05-27 09:30:00,000028,0.821255,0.821255,333.68,0.633283,0.633283
2021-05-28 09:30:00,000028,0.720266,0.720266,337.47,0.960843,0.960843
2021-05-31 09:30:00,000028,0.817308,0.817308,342.06,0.988649,0.988649
2021-06-01 09:30:00,000028,0.931537,0.931537,344.18,0.788095,0.788095

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000028,0.956700,0.956700,350.04,0.599213,0.599213
2021-05-27 09:30:00,000028,0.979992,0.979992,350.24,0.648930,0.648930
2021-05-28 09:30:00,000028,0.844540,0.844540,343.54,0.806817,0.806817
2021-05-31 09:30:00,000028,0.697724,0.697724,330.97,0.977580,0.977580
2021-06-01 09:30:00,000028,0.794356,0.794356,327.57,0.885524,0.885524

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000028,0.844157,0.844157,329.45,0.489848,0.489848
2021-05-27 09:30:00,000028,0.868605,0.868605,321.70,0.968245,0.968245
2021-05-28 09:30:00,000028,0.885872,0.885872,325.42,0.837722,0.837722
2021-05-31 09:30:00,000028,0.873761,0.873761,321.10,0.944408,0.944408
2021-06-01 09:30:00,000028,0.824923,0.824923,319.46,0.867359,0.867359

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000028,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000028,0.773583,0.773583,324.98,0.600383,0.600383
2021-05-27 09:30:00,000028,0.733187,0.733187,325.34,0.492847,0.492847
2021-05-28 09:30:00,000028,0.707264,0.707264,324.50,0.332051,0.332051
2021-05-31 09:30:00,000028,0.519308,0.519308,325.30,0.029167,0.029167
2021-06-01 09:30:00,000028,0.728430,0.728430,322.94,0.313504,0.313504

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000028,0.961009,0.961009,359.69,0.437642,0.437642
2020-01-03 09:30:00,000028,0.937357,0.937357,360.28,0.431077,0.431077
2020-01-06 09:30:00,000028,0.824719,0.824719,362.33,0.908116,0.908116
2020-01-07 09:30:00,000028,0.811923,0.811923,369.27,0.235177,0.235177
2020-01-08 09:30:00,000028,0.947721,0.947721,379.52,0.609098,0.609098
...,...,...,...,...,...,...
2021-05-26 09:30:00,000028,0.771926,0.771926,324.22,0.461235,0.461235
2021-05-27 09:30:00,000028,0.740924,0.740924,325.82,0.751608,0.751608
2021-05-28 09:30:00,000028,0.605846,0.605846,324.34,0.758437,0.758437
2021-05-31 09:30:00,000028,0.473994,0.473994,318.39,0.984441,0.984441
2021-06-01 09:30:00,000028,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000029,0.864126,0.864126,32.79,0.943966,0.943966
2021-05-27 09:30:00,000029,0.915495,0.915495,33.12,0.799889,0.799889
2021-05-28 09:30:00,000029,0.876511,0.876511,33.55,0.918622,0.918622
2021-05-31 09:30:00,000029,0.917584,0.917584,34.15,0.556569,0.556569
2021-06-01 09:30:00,000029,0.931262,0.931262,34.06,0.490719,0.490719

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000029,0.944875,0.944875,34.31,0.738290,0.738290
2021-05-27 09:30:00,000029,0.970073,0.970073,33.92,0.959856,0.959856
2021-05-28 09:30:00,000029,0.939724,0.939724,33.46,0.929129,0.929129
2021-05-31 09:30:00,000029,0.928705,0.928705,33.15,0.975021,0.975021
2021-06-01 09:30:00,000029,0.918903,0.918903,33.54,0.811781,0.811781

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000029,0.863296,0.863296,34.21,0.933432,0.933432
2021-05-27 09:30:00,000029,0.895459,0.895459,33.23,0.985725,0.985725
2021-05-28 09:30:00,000029,0.893370,0.893370,33.01,0.989361,0.989361
2021-05-31 09:30:00,000029,0.885888,0.885888,32.99,0.991979,0.991979
2021-06-01 09:30:00,000029,0.872992,0.872992,33.14,0.737723,0.737723

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000029,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000029,0.818174,0.818174,33.17,0.641817,0.641817
2021-05-27 09:30:00,000029,0.862959,0.862959,32.69,0.909079,0.909079
2021-05-28 09:30:00,000029,0.856138,0.856138,32.83,0.902721,0.902721
2021-05-31 09:30:00,000029,0.599629,0.599629,32.86,0.845669,0.845669
2021-06-01 09:30:00,000029,0.552148,0.552148,32.83,0.681433,0.681433

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000029,NaN,NaN,NaN,0.363393,0.363393
2020-01-03 09:30:00,000029,NaN,NaN,NaN,0.363393,0.363393
2020-01-06 09:30:00,000029,NaN,NaN,NaN,0.363393,0.363393
2020-01-07 09:30:00,000029,NaN,NaN,NaN,0.363393,0.363393
2020-01-08 09:30:00,000029,NaN,NaN,NaN,0.363393,0.363393
...,...,...,...,...,...,...
2021-05-26 09:30:00,000029,0.640060,0.640060,33.16,0.922831,0.922831
2021-05-27 09:30:00,000029,0.577394,0.577394,33.27,0.916262,0.916262
2021-05-28 09:30:00,000029,0.737438,0.737438,33.83,0.908041,0.908041
2021-05-31 09:30:00,000029,0.856821,0.856821,34.14,0.890867,0.890867
2021-06-01 09:30:00,000029,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000030,0.792527,0.792527,52.42,0.827173,0.827173
2021-05-27 09:30:00,000030,0.850087,0.850087,50.94,0.965095,0.965095
2021-05-28 09:30:00,000030,0.843374,0.843374,50.37,0.890141,0.890141
2021-05-31 09:30:00,000030,0.839784,0.839784,51.01,0.930456,0.930456
2021-06-01 09:30:00,000030,0.829069,0.829069,51.18,0.658038,0.658038

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000030,0.775828,0.775828,50.23,0.729879,0.729879
2021-05-27 09:30:00,000030,0.766442,0.766442,50.47,0.862596,0.862596
2021-05-28 09:30:00,000030,0.512844,0.512844,50.27,0.066082,0.066082
2021-05-31 09:30:00,000030,0.476010,0.476010,49.58,0.883146,0.883146
2021-06-01 09:30:00,000030,0.715194,0.715194,48.67,0.484702,0.484702

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000030,0.714966,0.714966,48.46,0.283785,0.283785
2021-05-27 09:30:00,000030,0.692414,0.692414,48.29,0.880575,0.880575
2021-05-28 09:30:00,000030,0.682167,0.682167,48.53,-0.103407,-0.103407
2021-05-31 09:30:00,000030,0.527842,0.527842,48.77,-0.702637,-0.702637
2021-06-01 09:30:00,000030,0.529078,0.529078,47.61,0.262103,0.262103

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000030,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000030,0.766776,0.766776,46.25,0.910667,0.910667
2021-05-27 09:30:00,000030,0.758766,0.758766,46.00,0.086995,0.086995
2021-05-28 09:30:00,000030,0.796470,0.796470,46.14,0.772073,0.772073
2021-05-31 09:30:00,000030,0.777925,0.777925,46.21,0.379451,0.379451
2021-06-01 09:30:00,000030,0.731406,0.731406,46.32,0.732991,0.732991

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000030,0.351351,0.351351,31.36,0.746411,0.746411
2020-01-03 09:30:00,000030,0.709683,0.709683,31.94,0.959130,0.959130
2020-01-06 09:30:00,000030,0.801815,0.801815,31.90,0.954082,0.954082
2020-01-07 09:30:00,000030,0.821630,0.821630,32.10,0.705031,0.705031
2020-01-08 09:30:00,000030,0.923241,0.923241,32.86,0.921973,0.921973
...,...,...,...,...,...,...
2021-05-26 09:30:00,000030,0.900686,0.900686,46.68,-0.261361,-0.261361
2021-05-27 09:30:00,000030,0.827510,0.827510,46.42,-0.101663,-0.101663
2021-05-28 09:30:00,000030,0.739943,0.739943,46.18,0.947181,0.947181
2021-05-31 09:30:00,000030,0.738934,0.738934,46.28,0.954737,0.954737
2021-06-01 09:30:00,000030,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000031,0.687051,0.687051,114.43,0.991415,0.991415
2021-05-27 09:30:00,000031,0.779858,0.779858,114.28,0.993015,0.993015
2021-05-28 09:30:00,000031,0.913252,0.913252,113.98,0.776922,0.776922
2021-05-31 09:30:00,000031,0.825636,0.825636,114.58,0.967258,0.967258
2021-06-01 09:30:00,000031,0.883821,0.883821,115.16,0.711057,0.711057

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000031,0.757394,0.757394,113.40,0.890654,0.890654
2021-05-27 09:30:00,000031,0.737305,0.737305,112.67,0.984895,0.984895
2021-05-28 09:30:00,000031,0.870349,0.870349,111.49,0.982493,0.982493
2021-05-31 09:30:00,000031,0.825921,0.825921,107.83,0.888487,0.888487
2021-06-01 09:30:00,000031,0.855411,0.855411,105.05,0.680116,0.680116

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000031,0.850711,0.850711,107.25,0.452069,0.452069
2021-05-27 09:30:00,000031,0.816323,0.816323,107.83,0.637138,0.637138
2021-05-28 09:30:00,000031,0.768941,0.768941,108.72,0.885275,0.885275
2021-05-31 09:30:00,000031,0.672920,0.672920,110.47,0.775069,0.775069
2021-06-01 09:30:00,000031,0.621861,0.621861,112.52,0.939210,0.939210

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000031,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000031,0.930582,0.930582,114.13,0.401360,0.401360
2021-05-27 09:30:00,000031,0.922951,0.922951,113.26,0.216214,0.216214
2021-05-28 09:30:00,000031,0.938404,0.938404,113.11,-0.307041,-0.307041
2021-05-31 09:30:00,000031,0.905434,0.905434,111.49,0.908047,0.908047
2021-06-01 09:30:00,000031,0.832475,0.832475,112.23,0.880159,0.880159

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000031,0.918670,0.918670,204.40,0.589866,0.589866
2020-01-03 09:30:00,000031,0.906600,0.906600,205.53,0.860921,0.860921
2020-01-06 09:30:00,000031,0.902547,0.902547,207.24,0.822183,0.822183
2020-01-07 09:30:00,000031,0.882859,0.882859,203.26,0.921740,0.921740
2020-01-08 09:30:00,000031,0.905751,0.905751,202.69,0.765209,0.765209
...,...,...,...,...,...,...
2021-05-26 09:30:00,000031,0.433359,0.433359,113.55,0.949032,0.949032
2021-05-27 09:30:00,000031,0.383456,0.383456,113.84,0.858037,0.858037
2021-05-28 09:30:00,000031,0.530812,0.530812,114.43,0.720690,0.720690
2021-05-31 09:30:00,000031,0.599362,0.599362,114.58,0.879648,0.879648
2021-06-01 09:30:00,000031,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000032,0.958336,0.958336,173.20,0.714342,0.714342
2021-05-27 09:30:00,000032,0.957825,0.957825,174.32,0.695688,0.695688
2021-05-28 09:30:00,000032,0.947122,0.947122,174.15,0.174195,0.174195
2021-05-31 09:30:00,000032,0.937836,0.937836,174.28,-0.196958,-0.196958
2021-06-01 09:30:00,000032,0.966659,0.966659,174.83,0.895716,0.895716

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000032,0.631810,0.631810,174.12,0.870160,0.870160
2021-05-27 09:30:00,000032,0.071056,0.071056,171.99,-0.026330,-0.026330
2021-05-28 09:30:00,000032,0.714413,0.714413,168.04,0.819270,0.819270
2021-05-31 09:30:00,000032,0.898470,0.898470,164.83,0.907875,0.907875
2021-06-01 09:30:00,000032,0.947503,0.947503,161.50,0.966502,0.966502

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000032,0.945187,0.945187,162.62,0.061998,0.061998
2021-05-27 09:30:00,000032,0.940253,0.940253,160.84,0.774624,0.774624
2021-05-28 09:30:00,000032,0.943664,0.943664,159.55,0.826080,0.826080
2021-05-31 09:30:00,000032,0.961973,0.961973,159.59,0.907308,0.907308
2021-06-01 09:30:00,000032,0.932345,0.932345,161.30,0.912409,0.912409

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000032,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000032,0.975715,0.975715,171.12,0.556262,0.556262
2021-05-27 09:30:00,000032,0.942966,0.942966,168.04,0.385561,0.385561
2021-05-28 09:30:00,000032,0.944523,0.944523,167.50,0.651615,0.651615
2021-05-31 09:30:00,000032,0.938236,0.938236,166.50,0.656459,0.656459
2021-06-01 09:30:00,000032,0.911366,0.911366,167.29,0.884854,0.884854

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000032,0.847221,0.847221,117.95,0.478459,0.478459
2020-01-03 09:30:00,000032,0.863842,0.863842,119.89,0.820308,0.820308
2020-01-06 09:30:00,000032,0.920190,0.920190,122.42,0.865270,0.865270
2020-01-07 09:30:00,000032,0.942701,0.942701,125.03,0.756933,0.756933
2020-01-08 09:30:00,000032,0.976295,0.976295,128.39,0.963713,0.963713
...,...,...,...,...,...,...
2021-05-26 09:30:00,000032,0.876083,0.876083,167.16,0.930298,0.930298
2021-05-27 09:30:00,000032,0.820199,0.820199,169.00,0.869604,0.869604
2021-05-28 09:30:00,000032,0.729089,0.729089,168.21,0.797842,0.797842
2021-05-31 09:30:00,000032,0.483882,0.483882,167.50,-0.395749,-0.395749
2021-06-01 09:30:00,000032,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000034,0.936353,0.936353,108.29,0.034060,0.034060
2021-05-27 09:30:00,000034,0.899661,0.899661,106.99,0.935686,0.935686
2021-05-28 09:30:00,000034,0.897616,0.897616,106.10,0.545570,0.545570
2021-05-31 09:30:00,000034,0.909495,0.909495,106.74,0.570771,0.570771
2021-06-01 09:30:00,000034,0.882489,0.882489,109.48,0.915937,0.915937

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000034,0.735385,0.735385,108.71,0.904762,0.904762
2021-05-27 09:30:00,000034,0.531839,0.531839,107.41,0.539055,0.539055
2021-05-28 09:30:00,000034,0.573111,0.573111,105.40,0.612776,0.612776
2021-05-31 09:30:00,000034,0.675688,0.675688,104.43,0.866966,0.866966
2021-06-01 09:30:00,000034,0.743029,0.743029,105.89,0.932099,0.932099

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000034,0.795899,0.795899,103.96,0.972327,0.972327
2021-05-27 09:30:00,000034,0.857095,0.857095,101.47,0.993993,0.993993
2021-05-28 09:30:00,000034,0.875376,0.875376,102.11,0.904369,0.904369
2021-05-31 09:30:00,000034,0.896213,0.896213,102.15,0.452190,0.452190
2021-06-01 09:30:00,000034,0.973584,0.973584,103.41,0.812029,0.812029

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000034,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000034,0.980988,0.980988,106.27,-0.098298,-0.098298
2021-05-27 09:30:00,000034,0.980871,0.980871,105.50,-0.194977,-0.194977
2021-05-28 09:30:00,000034,0.980483,0.980483,105.03,-0.262436,-0.262436
2021-05-31 09:30:00,000034,0.980620,0.980620,104.33,0.674833,0.674833
2021-06-01 09:30:00,000034,0.974819,0.974819,104.05,0.621381,0.621381

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000034,0.899441,0.899441,120.47,0.892072,0.892072
2020-01-03 09:30:00,000034,0.873554,0.873554,122.19,0.923426,0.923426
2020-01-06 09:30:00,000034,0.812956,0.812956,124.30,0.981782,0.981782
2020-01-07 09:30:00,000034,0.841826,0.841826,122.61,0.987349,0.987349
2020-01-08 09:30:00,000034,0.792219,0.792219,123.06,0.979818,0.979818
...,...,...,...,...,...,...
2021-05-26 09:30:00,000034,0.979972,0.979972,108.72,0.777404,0.777404
2021-05-27 09:30:00,000034,0.985881,0.985881,109.28,0.901379,0.901379
2021-05-28 09:30:00,000034,0.978358,0.978358,108.94,0.814847,0.814847
2021-05-31 09:30:00,000034,0.978610,0.978610,110.63,0.741173,0.741173
2021-06-01 09:30:00,000034,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000035,0.173937,0.173937,40.72,0.908057,0.908057
2021-05-27 09:30:00,000035,0.598679,0.598679,40.39,0.410282,0.410282
2021-05-28 09:30:00,000035,0.694824,0.694824,40.26,0.592887,0.592887
2021-05-31 09:30:00,000035,0.748575,0.748575,40.35,0.538476,0.538476
2021-06-01 09:30:00,000035,0.750478,0.750478,40.91,0.948969,0.948969

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000035,0.635893,0.635893,40.21,0.858202,0.858202
2021-05-27 09:30:00,000035,0.677319,0.677319,39.66,0.930840,0.930840
2021-05-28 09:30:00,000035,0.690816,0.690816,39.20,0.344167,0.344167
2021-05-31 09:30:00,000035,0.817646,0.817646,38.92,0.664489,0.664489
2021-06-01 09:30:00,000035,0.858175,0.858175,38.74,0.561851,0.561851

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000035,0.859928,0.859928,40.07,0.976639,0.976639
2021-05-27 09:30:00,000035,0.859928,0.859928,40.91,0.444196,0.444196
2021-05-28 09:30:00,000035,0.874007,0.874007,41.04,0.299353,0.299353
2021-05-31 09:30:00,000035,0.902491,0.902491,41.87,0.596179,0.596179
2021-06-01 09:30:00,000035,0.972307,0.972307,42.15,0.505839,0.505839

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000035,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000035,0.979437,0.979437,42.06,0.846708,0.846708
2021-05-27 09:30:00,000035,0.971350,0.971350,41.83,0.837193,0.837193
2021-05-28 09:30:00,000035,0.977836,0.977836,42.05,0.885101,0.885101
2021-05-31 09:30:00,000035,0.935312,0.935312,41.83,0.339722,0.339722
2021-06-01 09:30:00,000035,0.900277,0.900277,42.20,0.507772,0.507772

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000035,0.943564,0.943564,56.30,0.588806,0.588806
2020-01-03 09:30:00,000035,0.907381,0.907381,56.59,0.615442,0.615442
2020-01-06 09:30:00,000035,0.950455,0.950455,56.45,0.613595,0.613595
2020-01-07 09:30:00,000035,0.952087,0.952087,54.92,0.883491,0.883491
2020-01-08 09:30:00,000035,0.943750,0.943750,54.64,0.912036,0.912036
...,...,...,...,...,...,...
2021-05-26 09:30:00,000035,0.922378,0.922378,43.82,0.926954,0.926954
2021-05-27 09:30:00,000035,0.960139,0.960139,44.41,0.869975,0.869975
2021-05-28 09:30:00,000035,0.972681,0.972681,44.69,0.584688,0.584688
2021-05-31 09:30:00,000035,0.975955,0.975955,44.60,0.592552,0.592552
2021-06-01 09:30:00,000035,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000036,0.803376,0.803376,96.25,0.985807,0.985807
2021-05-27 09:30:00,000036,0.987787,0.987787,91.72,0.999772,0.999772
2021-05-28 09:30:00,000036,0.963342,0.963342,90.41,0.933963,0.933963
2021-05-31 09:30:00,000036,0.966160,0.966160,91.24,0.924490,0.924490
2021-06-01 09:30:00,000036,0.966480,0.966480,92.08,0.882487,0.882487

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000036,0.950694,0.950694,91.60,0.346048,0.346048
2021-05-27 09:30:00,000036,0.933363,0.933363,91.24,0.877837,0.877837
2021-05-28 09:30:00,000036,0.890228,0.890228,90.53,0.894015,0.894015
2021-05-31 09:30:00,000036,0.514501,0.514501,89.69,0.901371,0.901371
2021-06-01 09:30:00,000036,0.872153,0.872153,88.38,0.900336,0.900336

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000036,0.944024,0.944024,87.79,-0.218249,-0.218249
2021-05-27 09:30:00,000036,0.944867,0.944867,87.79,0.716874,0.716874
2021-05-28 09:30:00,000036,0.938057,0.938057,87.44,0.717609,0.717609
2021-05-31 09:30:00,000036,0.913983,0.913983,87.79,0.708974,0.708974
2021-06-01 09:30:00,000036,0.838449,0.838449,88.38,0.918633,0.918633

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000036,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000036,0.695347,0.695347,88.62,0.889675,0.889675
2021-05-27 09:30:00,000036,0.842274,0.842274,89.82,0.988449,0.988449
2021-05-28 09:30:00,000036,0.867435,0.867435,88.98,0.857678,0.857678
2021-05-31 09:30:00,000036,0.850787,0.850787,88.62,0.965520,0.965520
2021-06-01 09:30:00,000036,0.875816,0.875816,88.02,0.965970,0.965970

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000036,0.703680,0.703680,93.99,0.931129,0.931129
2020-01-03 09:30:00,000036,0.792674,0.792674,95.31,0.900690,0.900690
2020-01-06 09:30:00,000036,0.810113,0.810113,94.65,0.856246,0.856246
2020-01-07 09:30:00,000036,0.813634,0.813634,94.10,0.810589,0.810589
2020-01-08 09:30:00,000036,0.950752,0.950752,94.32,0.483261,0.483261
...,...,...,...,...,...,...
2021-05-26 09:30:00,000036,0.817800,0.817800,88.14,0.954389,0.954389
2021-05-27 09:30:00,000036,0.831437,0.831437,88.50,0.814575,0.814575
2021-05-28 09:30:00,000036,0.876928,0.876928,88.74,0.236558,0.236558
2021-05-31 09:30:00,000036,0.876057,0.876057,88.38,0.189741,0.189741
2021-06-01 09:30:00,000036,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000037,0.948774,0.948774,101.18,0.927352,0.927352
2021-05-27 09:30:00,000037,0.947449,0.947449,99.53,0.955893,0.955893
2021-05-28 09:30:00,000037,0.948462,0.948462,98.62,0.963651,0.963651
2021-05-31 09:30:00,000037,0.932853,0.932853,98.17,0.801752,0.801752
2021-06-01 09:30:00,000037,0.908198,0.908198,100.16,0.887396,0.887396

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000037,0.883980,0.883980,97.16,0.991521,0.991521
2021-05-27 09:30:00,000037,0.870146,0.870146,95.12,0.998522,0.998522
2021-05-28 09:30:00,000037,0.821396,0.821396,93.58,0.902941,0.902941
2021-05-31 09:30:00,000037,0.893342,0.893342,92.85,0.955505,0.955505
2021-06-01 09:30:00,000037,0.915462,0.915462,91.89,0.964068,0.964068

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000037,0.946305,0.946305,91.94,0.893522,0.893522
2021-05-27 09:30:00,000037,0.953239,0.953239,92.96,0.851515,0.851515
2021-05-28 09:30:00,000037,0.904783,0.904783,93.58,0.887154,0.887154
2021-05-31 09:30:00,000037,0.775547,0.775547,94.49,0.988869,0.988869
2021-06-01 09:30:00,000037,0.782672,0.782672,93.59,0.989507,0.989507

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000037,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000037,0.749789,0.749789,91.89,0.856218,0.856218
2021-05-27 09:30:00,000037,0.759597,0.759597,91.82,0.762034,0.762034
2021-05-28 09:30:00,000037,0.764320,0.764320,92.57,0.794545,0.794545
2021-05-31 09:30:00,000037,0.744847,0.744847,92.00,0.821018,0.821018
2021-06-01 09:30:00,000037,0.737680,0.737680,96.31,0.337040,0.337040

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000037,0.753469,0.753469,140.22,0.740641,0.740641
2020-01-03 09:30:00,000037,0.746206,0.746206,141.86,0.019706,0.019706
2020-01-06 09:30:00,000037,0.741890,0.741890,141.35,0.250119,0.250119
2020-01-07 09:30:00,000037,0.675879,0.675879,140.27,0.892711,0.892711
2020-01-08 09:30:00,000037,0.491580,0.491580,140.56,-0.225005,-0.225005
...,...,...,...,...,...,...
2021-05-26 09:30:00,000037,0.990301,0.990301,110.08,0.984634,0.984634
2021-05-27 09:30:00,000037,0.994127,0.994127,110.13,0.821093,0.821093
2021-05-28 09:30:00,000037,0.990044,0.990044,106.68,0.457804,0.457804
2021-05-31 09:30:00,000037,0.990419,0.990419,104.69,0.746865,0.746865
2021-06-01 09:30:00,000037,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000038,0.838789,0.838789,61.72,0.993594,0.993594
2021-05-27 09:30:00,000038,0.847669,0.847669,62.22,0.896277,0.896277
2021-05-28 09:30:00,000038,0.836176,0.836176,63.24,0.524780,0.524780
2021-05-31 09:30:00,000038,0.835981,0.835981,64.41,0.695408,0.695408
2021-06-01 09:30:00,000038,0.833827,0.833827,65.69,0.925913,0.925913

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000038,0.819969,0.819969,64.06,0.939767,0.939767
2021-05-27 09:30:00,000038,0.670170,0.670170,65.61,-0.604872,-0.604872
2021-05-28 09:30:00,000038,0.959407,0.959407,67.57,0.460458,0.460458
2021-05-31 09:30:00,000038,0.950277,0.950277,67.39,0.454455,0.454455
2021-06-01 09:30:00,000038,0.929578,0.929578,66.78,0.100995,0.100995

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000038,0.927438,0.927438,64.26,0.973550,0.973550
2021-05-27 09:30:00,000038,0.928370,0.928370,65.93,-0.109084,-0.109084
2021-05-28 09:30:00,000038,0.914143,0.914143,68.18,0.762463,0.762463
2021-05-31 09:30:00,000038,0.898259,0.898259,68.56,0.777889,0.777889
2021-06-01 09:30:00,000038,0.879859,0.879859,68.94,0.792593,0.792593

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000038,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000038,0.851945,0.851945,69.62,-0.654408,-0.654408
2021-05-27 09:30:00,000038,0.874393,0.874393,69.62,0.618523,0.618523
2021-05-28 09:30:00,000038,0.877208,0.877208,69.56,0.120046,0.120046
2021-05-31 09:30:00,000038,0.852312,0.852312,70.49,-0.336787,-0.336787
2021-06-01 09:30:00,000038,0.702698,0.702698,71.60,0.827953,0.827953

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000038,0.915022,0.915022,69.88,0.391842,0.391842
2020-01-03 09:30:00,000038,0.913389,0.913389,70.44,0.647776,0.647776
2020-01-06 09:30:00,000038,0.908687,0.908687,71.11,0.809194,0.809194
2020-01-07 09:30:00,000038,0.806047,0.806047,70.70,0.796181,0.796181
2020-01-08 09:30:00,000038,0.908786,0.908786,71.37,0.940569,0.940569
...,...,...,...,...,...,...
2021-05-26 09:30:00,000038,0.847929,0.847929,70.93,0.279956,0.279956
2021-05-27 09:30:00,000038,0.839262,0.839262,70.63,0.820691,0.820691
2021-05-28 09:30:00,000038,0.859048,0.859048,69.91,0.636121,0.636121
2021-05-31 09:30:00,000038,0.877163,0.877163,69.94,0.908313,0.908313
2021-06-01 09:30:00,000038,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000039,0.897682,0.897682,1027.14,0.697786,0.697786
2021-05-27 09:30:00,000039,0.862135,0.862135,1037.32,-0.244892,-0.244892
2021-05-28 09:30:00,000039,0.694147,0.694147,1015.42,0.889600,0.889600
2021-05-31 09:30:00,000039,0.709338,0.709338,1015.42,0.849071,0.849071
2021-06-01 09:30:00,000039,0.810194,0.810194,1009.56,0.334341,0.334341

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000039,0.762610,0.762610,986.74,0.873116,0.873116
2021-05-27 09:30:00,000039,0.818098,0.818098,975.94,0.982236,0.982236
2021-05-28 09:30:00,000039,0.854275,0.854275,975.32,0.981856,0.981856
2021-05-31 09:30:00,000039,0.882732,0.882732,971.92,0.956825,0.956825
2021-06-01 09:30:00,000039,0.784726,0.784726,975.01,0.739849,0.739849

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000039,0.686633,0.686633,1003.70,0.597984,0.597984
2021-05-27 09:30:00,000039,0.706168,0.706168,1007.40,0.839400,0.839400
2021-05-28 09:30:00,000039,0.802065,0.802065,1039.48,0.930402,0.930402
2021-05-31 09:30:00,000039,0.846902,0.846902,1041.02,0.874539,0.874539
2021-06-01 09:30:00,000039,0.815306,0.815306,1019.74,-0.502637,-0.502637

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000039,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000039,0.788543,0.788543,993.21,0.933891,0.933891
2021-05-27 09:30:00,000039,0.674217,0.674217,1000.93,0.945054,0.945054
2021-05-28 09:30:00,000039,0.694389,0.694389,1001.54,0.122075,0.122075
2021-05-31 09:30:00,000039,0.730466,0.730466,985.50,0.764873,0.764873
2021-06-01 09:30:00,000039,0.771531,0.771531,995.99,0.481980,0.481980

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000039,0.942132,0.942132,592.66,0.980242,0.980242
2020-01-03 09:30:00,000039,0.947259,0.947259,596.60,0.817748,0.817748
2020-01-06 09:30:00,000039,0.909897,0.909897,595.39,0.911043,0.911043
2020-01-07 09:30:00,000039,0.918197,0.918197,592.36,0.918275,0.918275
2020-01-08 09:30:00,000039,0.923800,0.923800,597.51,0.906883,0.906883
...,...,...,...,...,...,...
2021-05-26 09:30:00,000039,0.751530,0.751530,977.48,0.968921,0.968921
2021-05-27 09:30:00,000039,0.701775,0.701775,971.62,0.293055,0.293055
2021-05-28 09:30:00,000039,0.740807,0.740807,959.28,0.673139,0.673139
2021-05-31 09:30:00,000039,0.735204,0.735204,963.60,0.544608,0.544608
2021-06-01 09:30:00,000039,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000040,0.918108,0.918108,24.05,0.963575,0.963575
2021-05-27 09:30:00,000040,0.933387,0.933387,23.79,0.861325,0.861325
2021-05-28 09:30:00,000040,0.947348,0.947348,23.22,0.950903,0.950903
2021-05-31 09:30:00,000040,0.935792,0.935792,23.23,0.890916,0.890916
2021-06-01 09:30:00,000040,0.945857,0.945857,23.92,0.979059,0.979059

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000040,0.835276,0.835276,23.35,0.857603,0.857603
2021-05-27 09:30:00,000040,0.786449,0.786449,22.96,0.990239,0.990239
2021-05-28 09:30:00,000040,0.769536,0.769536,22.74,0.801610,0.801610
2021-05-31 09:30:00,000040,0.854991,0.854991,22.49,0.949605,0.949605
2021-06-01 09:30:00,000040,0.887197,0.887197,22.44,0.951864,0.951864

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000040,0.955882,0.955882,22.27,0.396925,0.396925
2021-05-27 09:30:00,000040,0.925002,0.925002,22.66,0.880539,0.880539
2021-05-28 09:30:00,000040,0.872886,0.872886,23.04,0.992423,0.992423
2021-05-31 09:30:00,000040,0.823276,0.823276,23.35,0.994808,0.994808
2021-06-01 09:30:00,000040,0.926430,0.926430,23.35,0.841250,0.841250

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000040,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000040,0.916301,0.916301,23.13,0.728388,0.728388
2021-05-27 09:30:00,000040,0.916211,0.916211,22.83,0.825915,0.825915
2021-05-28 09:30:00,000040,0.886963,0.886963,22.74,0.737771,0.737771
2021-05-31 09:30:00,000040,0.845000,0.845000,22.49,0.947622,0.947622
2021-06-01 09:30:00,000040,0.843895,0.843895,22.70,-0.075706,-0.075706

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000040,0.893490,0.893490,36.66,0.432972,0.432972
2020-01-03 09:30:00,000040,0.906795,0.906795,36.88,0.073948,0.073948
2020-01-06 09:30:00,000040,0.938404,0.938404,37.44,0.716333,0.716333
2020-01-07 09:30:00,000040,0.948012,0.948012,37.66,0.729951,0.729951
2020-01-08 09:30:00,000040,0.974783,0.974783,38.71,0.967572,0.967572
...,...,...,...,...,...,...
2021-05-26 09:30:00,000040,0.872518,0.872518,23.13,0.524960,0.524960
2021-05-27 09:30:00,000040,0.856871,0.856871,23.09,0.449909,0.449909
2021-05-28 09:30:00,000040,0.842981,0.842981,22.96,0.647621,0.647621
2021-05-31 09:30:00,000040,0.815188,0.815188,22.87,0.719181,0.719181
2021-06-01 09:30:00,000040,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000042,0.256181,0.256181,235.15,0.135383,0.135383
2021-05-27 09:30:00,000042,0.302830,0.302830,231.40,0.974941,0.974941
2021-05-28 09:30:00,000042,0.602251,0.602251,228.60,0.436860,0.436860
2021-05-31 09:30:00,000042,0.670483,0.670483,233.81,0.287300,0.287300
2021-06-01 09:30:00,000042,0.703291,0.703291,236.75,0.519097,0.519097

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000042,0.763566,0.763566,236.47,0.910659,0.910659
2021-05-27 09:30:00,000042,0.746136,0.746136,234.60,0.479184,0.479184
2021-05-28 09:30:00,000042,0.746663,0.746663,231.54,0.913577,0.913577
2021-05-31 09:30:00,000042,0.763308,0.763308,231.93,0.932168,0.932168
2021-06-01 09:30:00,000042,0.910853,0.910853,230.20,0.732621,0.732621

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000042,0.905982,0.905982,226.74,0.929739,0.929739
2021-05-27 09:30:00,000042,0.930600,0.930600,226.20,0.935718,0.935718
2021-05-28 09:30:00,000042,0.908187,0.908187,225.39,0.973299,0.973299
2021-05-31 09:30:00,000042,0.906613,0.906613,225.53,0.984383,0.984383
2021-06-01 09:30:00,000042,0.937966,0.937966,227.40,0.987527,0.987527

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000042,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000042,0.920856,0.920856,228.34,0.773530,0.773530
2021-05-27 09:30:00,000042,0.867008,0.867008,227.54,0.716557,0.716557
2021-05-28 09:30:00,000042,0.854781,0.854781,230.34,0.762628,0.762628
2021-05-31 09:30:00,000042,0.843098,0.843098,230.07,0.658002,0.658002
2021-06-01 09:30:00,000042,0.836737,0.836737,229.27,0.834254,0.834254

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000042,0.944536,0.944536,288.63,0.627320,0.627320
2020-01-03 09:30:00,000042,0.964028,0.964028,288.50,0.658378,0.658378
2020-01-06 09:30:00,000042,0.948183,0.948183,285.73,0.916458,0.916458
2020-01-07 09:30:00,000042,0.914404,0.914404,284.28,0.932559,0.932559
2020-01-08 09:30:00,000042,0.871350,0.871350,285.07,0.438081,0.438081
...,...,...,...,...,...,...
2021-05-26 09:30:00,000042,0.760329,0.760329,231.14,0.441937,0.441937
2021-05-27 09:30:00,000042,0.647058,0.647058,231.94,0.858168,0.858168
2021-05-28 09:30:00,000042,0.618331,0.618331,232.34,0.957671,0.957671
2021-05-31 09:30:00,000042,0.835224,0.835224,231.67,0.671109,0.671109
2021-06-01 09:30:00,000042,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000045,0.493668,0.493668,46.29,0.243262,0.243262
2021-05-27 09:30:00,000045,0.519110,0.519110,47.40,0.306779,0.306779
2021-05-28 09:30:00,000045,0.577095,0.577095,47.84,0.085808,0.085808
2021-05-31 09:30:00,000045,0.568657,0.568657,47.90,0.274251,0.274251
2021-06-01 09:30:00,000045,0.582111,0.582111,48.36,0.627453,0.627453

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000045,0.465514,0.465514,47.19,0.752391,0.752391
2021-05-27 09:30:00,000045,0.471599,0.471599,47.51,0.828395,0.828395
2021-05-28 09:30:00,000045,0.901683,0.901683,48.02,0.883012,0.883012
2021-05-31 09:30:00,000045,0.904685,0.904685,49.01,0.773971,0.773971
2021-06-01 09:30:00,000045,0.772801,0.772801,48.84,0.775382,0.775382

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000045,0.755477,0.755477,48.48,0.971095,0.971095
2021-05-27 09:30:00,000045,0.733054,0.733054,47.89,0.962803,0.962803
2021-05-28 09:30:00,000045,0.732839,0.732839,46.14,0.980222,0.980222
2021-05-31 09:30:00,000045,0.834706,0.834706,45.50,0.860175,0.860175
2021-06-01 09:30:00,000045,0.860365,0.860365,47.14,0.503721,0.503721

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000045,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000045,0.913995,0.913995,48.86,0.780059,0.780059
2021-05-27 09:30:00,000045,0.885017,0.885017,48.74,0.804639,0.804639
2021-05-28 09:30:00,000045,0.892387,0.892387,48.39,0.135794,0.135794
2021-05-31 09:30:00,000045,0.900848,0.900848,47.95,0.585500,0.585500
2021-06-01 09:30:00,000045,0.902370,0.902370,48.28,-0.560010,-0.560010

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000045,0.761483,0.761483,43.89,0.795664,0.795664
2020-01-03 09:30:00,000045,0.666046,0.666046,44.27,0.789609,0.789609
2020-01-06 09:30:00,000045,0.573787,0.573787,44.85,0.962522,0.962522
2020-01-07 09:30:00,000045,0.667446,0.667446,45.67,0.895853,0.895853
2020-01-08 09:30:00,000045,0.936651,0.936651,46.08,0.609350,0.609350
...,...,...,...,...,...,...
2021-05-26 09:30:00,000045,0.930064,0.930064,50.18,0.960418,0.960418
2021-05-27 09:30:00,000045,0.886744,0.886744,50.33,0.950862,0.950862
2021-05-28 09:30:00,000045,0.920110,0.920110,51.27,0.798157,0.798157
2021-05-31 09:30:00,000045,0.906446,0.906446,51.74,0.787518,0.787518
2021-06-01 09:30:00,000045,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000046,0.639270,0.639270,190.10,0.590658,0.590658
2021-05-27 09:30:00,000046,0.821010,0.821010,189.76,0.589084,0.589084
2021-05-28 09:30:00,000046,0.831141,0.831141,185.34,0.954584,0.954584
2021-05-31 09:30:00,000046,0.893878,0.893878,189.76,-0.141178,-0.141178
2021-06-01 09:30:00,000046,0.922652,0.922652,194.52,0.278527,0.278527

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000046,0.924951,0.924951,190.10,0.478644,0.478644
2021-05-27 09:30:00,000046,0.936519,0.936519,187.04,0.919631,0.919631
2021-05-28 09:30:00,000046,0.967416,0.967416,183.64,0.974481,0.974481
2021-05-31 09:30:00,000046,0.961019,0.961019,181.25,0.984771,0.984771
2021-06-01 09:30:00,000046,0.966884,0.966884,179.89,0.791657,0.791657

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000046,0.950012,0.950012,188.74,0.940940,0.940940
2021-05-27 09:30:00,000046,0.945222,0.945222,196.22,0.987774,0.987774
2021-05-28 09:30:00,000046,0.949454,0.949454,198.94,0.935945,0.935945
2021-05-31 09:30:00,000046,0.952277,0.952277,196.90,0.805243,0.805243
2021-06-01 09:30:00,000046,0.960052,0.960052,198.26,0.774121,0.774121

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000046,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000046,0.969277,0.969277,194.52,0.987414,0.987414
2021-05-27 09:30:00,000046,0.949039,0.949039,190.10,0.998309,0.998309
2021-05-28 09:30:00,000046,0.922471,0.922471,190.10,0.961142,0.961142
2021-05-31 09:30:00,000046,0.900087,0.900087,189.08,0.976308,0.976308
2021-06-01 09:30:00,000046,0.923233,0.923233,187.72,0.968000,0.968000

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000046,0.740384,0.740384,302.52,-0.739397,-0.739397
2020-01-03 09:30:00,000046,0.807447,0.807447,307.18,0.831355,0.831355
2020-01-06 09:30:00,000046,0.819862,0.819862,307.19,0.888163,0.888163
2020-01-07 09:30:00,000046,0.824165,0.824165,305.85,0.927134,0.927134
2020-01-08 09:30:00,000046,0.965493,0.965493,308.85,0.826183,0.826183
...,...,...,...,...,...,...
2021-05-26 09:30:00,000046,0.947409,0.947409,184.66,0.992884,0.992884
2021-05-27 09:30:00,000046,0.938438,0.938438,192.48,0.621202,0.621202
2021-05-28 09:30:00,000046,0.928048,0.928048,198.94,0.693457,0.693457
2021-05-31 09:30:00,000046,0.922036,0.922036,194.18,0.696268,0.696268
2021-06-01 09:30:00,000046,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000048,0.751011,0.751011,334.73,0.580349,0.580349
2021-05-27 09:30:00,000048,0.780387,0.780387,335.79,0.458496,0.458496
2021-05-28 09:30:00,000048,0.862735,0.862735,340.87,0.963039,0.963039
2021-05-31 09:30:00,000048,0.946040,0.946040,341.17,0.578550,0.578550
2021-06-01 09:30:00,000048,0.940970,0.940970,344.87,0.167266,0.167266

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000048,0.943799,0.943799,342.80,0.282884,0.282884
2021-05-27 09:30:00,000048,0.894079,0.894079,342.99,0.243336,0.243336
2021-05-28 09:30:00,000048,0.832591,0.832591,344.50,0.306669,0.306669
2021-05-31 09:30:00,000048,0.547342,0.547342,341.87,0.947653,0.947653
2021-06-01 09:30:00,000048,0.352964,0.352964,342.93,0.560182,0.560182

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000048,0.904664,0.904664,367.59,0.792272,0.792272
2021-05-27 09:30:00,000048,0.926865,0.926865,368.59,0.588643,0.588643
2021-05-28 09:30:00,000048,0.925975,0.925975,NaN,0.588643,0.588643
2021-05-31 09:30:00,000048,0.841254,0.841254,352.80,0.977688,0.977688
2021-06-01 09:30:00,000048,0.841511,0.841511,350.47,0.824537,0.824537

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000048,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000048,0.662655,0.662655,360.85,0.525666,0.525666
2021-05-27 09:30:00,000048,0.709439,0.709439,363.76,-0.424037,-0.424037
2021-05-28 09:30:00,000048,0.752461,0.752461,365.99,-0.080623,-0.080623
2021-05-31 09:30:00,000048,0.729895,0.729895,358.88,0.494863,0.494863
2021-06-01 09:30:00,000048,0.649139,0.649139,353.31,0.906880,0.906880

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000048,0.456914,0.456914,261.46,0.953140,0.953140
2020-01-03 09:30:00,000048,0.284639,0.284639,265.17,0.583954,0.583954
2020-01-06 09:30:00,000048,0.196712,0.196712,266.15,0.671542,0.671542
2020-01-07 09:30:00,000048,0.217865,0.217865,267.79,0.544737,0.544737
2020-01-08 09:30:00,000048,0.900758,0.900758,273.01,0.976998,0.976998
...,...,...,...,...,...,...
2021-05-26 09:30:00,000048,0.862019,0.862019,346.88,0.967832,0.967832
2021-05-27 09:30:00,000048,0.864313,0.864313,346.88,0.940266,0.940266
2021-05-28 09:30:00,000048,0.834287,0.834287,341.30,0.925492,0.925492
2021-05-31 09:30:00,000048,0.896736,0.896736,337.70,0.230208,0.230208
2021-06-01 09:30:00,000048,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000049,0.686625,0.686625,741.06,0.758961,0.758961
2021-05-27 09:30:00,000049,0.674852,0.674852,749.20,0.149131,0.149131
2021-05-28 09:30:00,000049,0.695617,0.695617,747.38,0.215350,0.215350
2021-05-31 09:30:00,000049,0.726075,0.726075,745.12,0.259303,0.259303
2021-06-01 09:30:00,000049,0.743299,0.743299,752.38,0.730432,0.730432

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000049,0.669045,0.669045,768.76,0.877284,0.877284
2021-05-27 09:30:00,000049,0.716196,0.716196,781.01,0.924513,0.924513
2021-05-28 09:30:00,000049,0.943026,0.943026,784.41,0.982027,0.982027
2021-05-31 09:30:00,000049,0.935121,0.935121,790.52,0.968209,0.968209
2021-06-01 09:30:00,000049,0.948285,0.948285,792.49,0.458049,0.458049

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000049,0.887254,0.887254,795.62,0.991561,0.991561
2021-05-27 09:30:00,000049,0.714905,0.714905,791.84,0.702680,0.702680
2021-05-28 09:30:00,000049,0.622640,0.622640,772.88,0.955523,0.955523
2021-05-31 09:30:00,000049,0.539640,0.539640,NaN,0.955523,0.955523
2021-06-01 09:30:00,000049,0.715625,0.715625,742.76,0.995274,0.995274

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000049,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000049,0.919690,0.919690,701.29,0.606618,0.606618
2021-05-27 09:30:00,000049,0.936255,0.936255,700.81,0.286569,0.286569
2021-05-28 09:30:00,000049,0.934352,0.934352,702.10,0.465116,0.465116
2021-05-31 09:30:00,000049,0.943396,0.943396,700.57,0.280774,0.280774
2021-06-01 09:30:00,000049,0.888502,0.888502,691.11,0.872995,0.872995

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000049,0.850191,0.850191,440.86,0.643756,0.643756
2020-01-03 09:30:00,000049,0.805853,0.805853,448.94,0.833757,0.833757
2020-01-06 09:30:00,000049,0.824513,0.824513,454.91,0.933284,0.933284
2020-01-07 09:30:00,000049,0.843896,0.843896,460.54,0.747720,0.747720
2020-01-08 09:30:00,000049,0.893049,0.893049,465.58,0.166681,0.166681
...,...,...,...,...,...,...
2021-05-26 09:30:00,000049,0.816956,0.816956,679.96,0.856845,0.856845
2021-05-27 09:30:00,000049,0.517713,0.517713,684.32,0.836182,0.836182
2021-05-28 09:30:00,000049,0.757356,0.757356,686.10,0.537650,0.537650
2021-05-31 09:30:00,000049,0.724598,0.724598,692.64,0.766353,0.766353
2021-06-01 09:30:00,000049,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000050,0.801442,0.801442,233.44,0.976218,0.976218
2021-05-27 09:30:00,000050,0.858418,0.858418,234.95,0.453049,0.453049
2021-05-28 09:30:00,000050,0.856502,0.856502,235.53,0.168897,0.168897
2021-05-31 09:30:00,000050,0.852744,0.852744,236.11,-0.223229,-0.223229
2021-06-01 09:30:00,000050,0.858499,0.858499,238.21,0.855240,0.855240

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000050,0.853172,0.853172,238.46,0.342398,0.342398
2021-05-27 09:30:00,000050,0.845034,0.845034,237.21,0.930473,0.930473
2021-05-28 09:30:00,000050,0.890646,0.890646,237.87,-0.037742,-0.037742
2021-05-31 09:30:00,000050,0.813464,0.813464,237.46,0.623679,0.623679
2021-06-01 09:30:00,000050,0.691793,0.691793,237.03,0.412383,0.412383

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000050,0.903448,0.903448,229.75,0.960579,0.960579
2021-05-27 09:30:00,000050,0.950918,0.950918,226.82,0.938564,0.938564
2021-05-28 09:30:00,000050,0.950298,0.950298,225.99,0.892832,0.892832
2021-05-31 09:30:00,000050,0.955727,0.955727,226.91,0.743484,0.743484
2021-06-01 09:30:00,000050,0.953005,0.953005,228.16,0.369792,0.369792

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000050,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000050,0.892471,0.892471,231.18,0.815088,0.815088
2021-05-27 09:30:00,000050,0.871716,0.871716,230.09,0.545989,0.545989
2021-05-28 09:30:00,000050,0.747509,0.747509,229.16,0.844335,0.844335
2021-05-31 09:30:00,000050,0.776558,0.776558,227.66,0.942933,0.942933
2021-06-01 09:30:00,000050,0.858555,0.858555,226.90,0.928888,0.928888

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000050,0.824296,0.824296,270.41,0.703530,0.703530
2020-01-03 09:30:00,000050,0.788057,0.788057,276.16,0.869813,0.869813
2020-01-06 09:30:00,000050,0.749690,0.749690,279.32,0.938175,0.938175
2020-01-07 09:30:00,000050,0.735846,0.735846,280.73,0.304105,0.304105
2020-01-08 09:30:00,000050,0.779912,0.779912,283.98,0.707776,0.707776
...,...,...,...,...,...,...
2021-05-26 09:30:00,000050,0.809826,0.809826,228.92,0.972938,0.972938
2021-05-27 09:30:00,000050,0.802612,0.802612,229.76,0.678829,0.678829
2021-05-28 09:30:00,000050,0.787977,0.787977,230.84,0.677803,0.677803
2021-05-31 09:30:00,000050,0.678662,0.678662,230.17,0.188725,0.188725
2021-06-01 09:30:00,000050,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000055,0.550776,0.550776,86.00,0.745668,0.745668
2021-05-27 09:30:00,000055,0.739972,0.739972,85.60,0.666206,0.666206
2021-05-28 09:30:00,000055,0.805592,0.805592,85.60,0.466454,0.466454
2021-05-31 09:30:00,000055,0.785384,0.785384,86.38,0.758399,0.758399
2021-06-01 09:30:00,000055,0.793180,0.793180,87.46,0.862879,0.862879

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000055,0.807869,0.807869,87.76,0.448087,0.448087
2021-05-27 09:30:00,000055,0.769973,0.769973,87.46,0.775393,0.775393
2021-05-28 09:30:00,000055,0.780763,0.780763,86.87,0.440085,0.440085
2021-05-31 09:30:00,000055,0.858114,0.858114,86.58,0.949388,0.949388
2021-06-01 09:30:00,000055,0.858114,0.858114,85.01,0.893690,0.893690

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000055,0.938820,0.938820,83.15,0.903603,0.903603
2021-05-27 09:30:00,000055,0.942609,0.942609,83.25,0.829597,0.829597
2021-05-28 09:30:00,000055,0.942799,0.942799,83.35,-0.353268,-0.353268
2021-05-31 09:30:00,000055,0.950146,0.950146,83.94,-0.658128,-0.658128
2021-06-01 09:30:00,000055,0.925528,0.925528,84.13,-0.030241,-0.030241

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000055,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000055,0.909427,0.909427,87.16,0.996641,0.996641
2021-05-27 09:30:00,000055,0.913336,0.913336,85.31,0.980829,0.980829
2021-05-28 09:30:00,000055,0.961328,0.961328,84.53,0.973268,0.973268
2021-05-31 09:30:00,000055,0.957156,0.957156,83.65,0.968303,0.968303
2021-06-01 09:30:00,000055,0.971944,0.971944,84.13,0.518520,0.518520

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000055,0.839045,0.839045,92.35,0.980270,0.980270
2020-01-03 09:30:00,000055,0.904549,0.904549,93.61,0.970608,0.970608
2020-01-06 09:30:00,000055,0.920171,0.920171,92.93,0.849338,0.849338
2020-01-07 09:30:00,000055,0.936586,0.936586,92.44,0.885869,0.885869
2020-01-08 09:30:00,000055,0.985791,0.985791,93.71,0.978646,0.978646
...,...,...,...,...,...,...
2021-05-26 09:30:00,000055,0.968602,0.968602,84.72,0.596880,0.596880
2021-05-27 09:30:00,000055,0.942001,0.942001,85.11,0.865354,0.865354
2021-05-28 09:30:00,000055,0.812996,0.812996,85.60,0.980418,0.980418
2021-05-31 09:30:00,000055,0.783099,0.783099,85.60,0.931406,0.931406
2021-06-01 09:30:00,000055,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000056,0.967069,0.967069,30.37,0.768180,0.768180
2021-05-27 09:30:00,000056,0.964663,0.964663,31.03,0.971173,0.971173
2021-05-28 09:30:00,000056,0.963972,0.963972,31.31,0.306560,0.306560
2021-05-31 09:30:00,000056,0.953459,0.953459,32.06,0.510930,0.510930
2021-06-01 09:30:00,000056,0.944470,0.944470,32.53,0.635881,0.635881

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000056,0.855120,0.855120,33.81,0.101471,0.101471
2021-05-27 09:30:00,000056,0.864215,0.864215,33.39,-0.161707,-0.161707
2021-05-28 09:30:00,000056,0.852347,0.852347,30.79,0.831859,0.831859
2021-05-31 09:30:00,000056,0.823468,0.823468,32.54,0.689554,0.689554
2021-06-01 09:30:00,000056,0.813672,0.813672,32.12,-0.375245,-0.375245

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000056,0.730399,0.730399,33.01,0.868316,0.868316
2021-05-27 09:30:00,000056,0.717958,0.717958,33.52,-0.255466,-0.255466
2021-05-28 09:30:00,000056,0.742309,0.742309,34.42,0.734885,0.734885
2021-05-31 09:30:00,000056,0.795714,0.795714,35.36,0.880216,0.880216
2021-06-01 09:30:00,000056,0.924067,0.924067,36.35,0.939385,0.939385

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000056,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000056,0.906564,0.906564,40.21,0.588835,0.588835
2021-05-27 09:30:00,000056,0.852280,0.852280,37.34,0.924168,0.924168
2021-05-28 09:30:00,000056,0.805560,0.805560,34.75,0.904436,0.904436
2021-05-31 09:30:00,000056,0.780937,0.780937,35.64,0.809272,0.809272
2021-06-01 09:30:00,000056,0.753153,0.753153,37.76,0.824850,0.824850

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000056,0.902655,0.902655,39.08,0.981084,0.981084
2020-01-03 09:30:00,000056,0.855450,0.855450,39.55,0.929106,0.929106
2020-01-06 09:30:00,000056,0.750041,0.750041,40.16,0.987670,0.987670
2020-01-07 09:30:00,000056,0.583192,0.583192,40.31,0.892339,0.892339
2020-01-08 09:30:00,000056,0.761350,0.761350,40.73,0.906270,0.906270
...,...,...,...,...,...,...
2021-05-26 09:30:00,000056,0.740070,0.740070,38.37,0.491095,0.491095
2021-05-27 09:30:00,000056,0.744288,0.744288,37.76,0.603049,0.603049
2021-05-28 09:30:00,000056,0.761112,0.761112,39.31,-0.218450,-0.218450
2021-05-31 09:30:00,000056,0.833645,0.833645,39.98,0.763891,0.763891
2021-06-01 09:30:00,000056,NaN,NaN,NaN,NaN,NaN

,,test_mcorr_open_low_10,test_1,test,"ewmCorr(high,low)","ewmCorr(high,low,7)"
timestamp,ticker,,,,,
2020-01-02 09:30:00,000058,NaN,NaN,NaN,NaN,NaN
2020-01-03 09:30:00,000058,NaN,NaN,NaN,NaN,NaN
2020-01-06 09:30:00,000058,NaN,NaN,NaN,NaN,NaN
2020-01-07 09:30:00,000058,NaN,NaN,NaN,NaN,NaN
2020-01-08 09:30:00,000058,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-05-26 09:30:00,000058,0.749470,0.749470,38.90,0.892558,0.892558
2021-05-27 09:30:00,000058,0.822394,0.822394,38.54,0.629442,0.629442
2021-05-28 09:30:00,000058,0.801271,0.801271,39.16,0.745520,0.745520
2021-05-31 09:30:00,000058,0.826455,0.826455,39.10,0.450126,0.450126
2021-06-01 09:30:00,000058,0.833142,0.833142,40.05,0.933368,0.933368

KeyboardInterrupt: