In [50]:
import pandas as pd
import numpy as np
import torch
from torch import nn as nn

In [237]:
data = pd.read_csv('alphanet_codetest_daily.csv')
data['timestamp'] = pd.to_datetime(data.timestamp.astype('str'))
data['unix'] = data['timestamp'].astype('int64')//1e9
one_data = data[data['ticker'] == 1]
data

,timestamp,ticker,pre_close,open,close,high,low,vwap,chg,pct_chg,volume,amount,turnover,free_turnover,fq_factor,high_limit,low_limit,trading_status,unix
0,2019-09-23,1,15.34,15.34,15.38,15.47,15.18,15.3122,0.04,0.2608,1403282.00,2148740.448,0.7428,1.5038,109.169427,16.87,13.81,-1.0,1569196800
1,2019-09-23,2,26.80,26.49,26.15,26.49,26.00,26.1471,-0.65,-2.4254,603530.46,1578059.535,0.6212,1.0882,148.411917,29.48,24.12,-1.0,1569196800
2,2019-09-23,4,21.03,20.36,20.04,20.65,19.61,20.0171,-0.99,-4.7076,29893.32,59837.839,3.6188,5.9394,4.063862,23.13,18.93,-1.0,1569196800
3,2019-09-23,5,3.37,3.37,3.30,3.37,3.27,3.2947,-0.07,-2.0772,111437.30,36714.744,1.0533,1.3495,9.267603,3.71,3.03,-1.0,1569196800
4,2019-09-23,6,5.32,5.34,5.38,5.40,5.21,5.2993,0.06,1.1278,136997.47,72599.425,1.0161,1.5887,35.425960,5.85,4.79,-1.0,1569196800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1958382,2021-09-23,688798,234.00,234.10,240.33,241.79,230.51,237.5860,6.33,2.7051,5033.35,119585.342,1.5740,1.5740,1.000000,280.80,187.20,-1.0,1632355200
1958383,2021-09-23,688799,40.38,40.23,40.00,40.99,39.88,40.2658,-0.38,-0.9411,6743.58,27153.556,3.5254,3.5254,1.000000,48.46,32.30,-1.0,1632355200
1958384,2021-09-23,688800,78.40,79.44,80.00,81.05,75.85,78.1837,1.60,2.0408,7087.72,55414.441,3.2259,3.2259,1.000000,94.08,62.72,-1.0,1632355200
1958385,2021-09-23,688819,44.89,45.08,44.58,45.20,44.28,44.7130,-0.31,-0.6906,25476.27,113912.164,2.3983,2.3983,1.014728,53.87,35.91,-1.0,1632355200
1958386,2021-09-23,688981,55.25,55.35,55.33,55.88,55.20,55.4847,0.08,0.1448,232030.82,1287415.623,1.2401,1.2401,1.000000,66.30,44.20,-1.0,1632355200

In [96]:
start_time = "2019-09-23"
start_time = int(pd.to_datetime(start_time).value // 1e9)
end_time = "2021-09-23"
end_time = int(pd.to_datetime(end_time).value // 1e9)

1632355200

In [222]:
delay = 30 # 设置delay的天数
one_data['pct_change_shift'] = (one_data['close'].shift(-2) - one_data['close']) / one_data['close'] * 100
one_data = one_data[['timestamp','ticker','open','high','low','close','vwap','volume','pct_chg','turnover','free_turnover','pct_change_shift']]
one_data = one_data.set_index(['timestamp','ticker'])
delay_data = one_data.shift(delay)
one_data

C:\Users\Xinfei\AppData\Local\Temp/ipykernel_15068/3069651485.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_data['pct_change_shift'] = (one_data['close'].shift(-2) - one_data['close']) / one_data['close'] * 100

,,open,high,low,close,vwap,volume,pct_chg,turnover,free_turnover,pct_change_shift
timestamp,ticker,,,,,,,,,,
2019-09-23,1,15.34,15.47,15.18,15.38,15.3122,1403282.00,0.2608,0.7428,1.5038,2.405722
2019-09-24,1,15.47,15.54,15.18,15.18,15.2886,1129103.24,-1.3004,0.5977,1.2100,3.491436
2019-09-25,1,15.20,15.85,15.19,15.75,15.5996,1938892.72,3.7549,1.0263,2.0778,0.952381
2019-09-26,1,15.86,16.04,15.66,15.71,15.8491,1686592.58,-0.2540,0.8928,1.8074,-0.763845
2019-09-27,1,15.85,16.00,15.70,15.90,15.8634,1007706.27,1.2094,0.5193,1.0235,1.886792
...,...,...,...,...,...,...,...,...,...,...,...
2021-09-15,1,19.31,20.99,19.19,19.52,19.4779,841618.41,0.7744,0.4337,0.9785,-5.071721
2021-09-16,1,19.30,19.50,18.73,19.08,18.9852,1176953.56,-2.2541,0.6065,1.3684,-5.765199
2021-09-17,1,18.90,19.00,18.41,18.53,18.6572,1124879.63,-2.8826,0.5797,1.3078,-4.587156
2021-09-22,1,17.87,18.05,17.42,17.98,17.7601,1473365.21,-2.9682,0.7592,1.7130,NaN
2021-09-23,1,18.10,18.32,17.65,17.68,17.8694,1379837.59,-1.6685,0.7110,1.6043,NaN

In [223]:
delay_data

,,open,high,low,close,vwap,volume,pct_chg,turnover,free_turnover,pct_change_shift
timestamp,ticker,,,,,,,,,,
2019-09-23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-24,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-26,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-27,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2021-09-15,1,18.04,18.07,17.60,17.81,17.8197,729620.08,-0.4472,0.3760,0.8483,0.280741
2021-09-16,1,17.70,18.05,17.58,17.68,17.7759,621573.88,-0.7299,0.3203,0.7227,7.805430
2021-09-17,1,17.55,17.90,17.45,17.86,17.7260,567454.13,1.0181,0.2924,0.6597,10.470325
2021-09-22,1,17.91,19.25,17.84,19.06,18.9058,1752798.00,6.7189,0.9032,2.0379,3.934942
2021-09-23,1,19.09,19.98,18.90,19.73,19.4735,1301988.44,3.5152,0.6709,1.5137,0.810948

In [236]:
array = np.array(one_data)
delay_array = np.array(delay_data)
day = 3
x , y , x_delay = [] , [], []
# for i in range(0,array.shape[0] - day ,3): # 其中3 代表取数的步长，ex.每两天取一次数，步长为3
for i in range(delay,delay + 3 ,3): # 其中3 代表取数的步长，ex.每两天取一次数，步长为3
    x.append(array[i:i+day,:-1].T)
    y.append(array[i+day-1][-1])
    x_delay.append(delay_array[i:i+day,:-1].T)
#     print(array[i:i+day,:-1])
#     print(array[i+day-1][-1]) # y
x  , y , x_delay= np.array(x) , np.array(y).reshape(-1,1) , np.array(x_delay) # x = (153, 9, 30) , y = (153,1)
x = x.reshape(x.shape[0],1,x.shape[1],x.shape[2]) # x = (153, 1, 9, 30)
x_delay = x_delay.reshape(x_delay.shape[0],1,x_delay.shape[1],x_delay.shape[2]) # x = (153, 1, 9, 30)
x_delay = (x-x_delay)/x_delay
x_delay

array([[[[ 1.53400000e+01,  1.54700000e+01,  1.52000000e+01],
         [ 1.54700000e+01,  1.55400000e+01,  1.58500000e+01],
         [ 1.51800000e+01,  1.51800000e+01,  1.51900000e+01],
         [ 1.53800000e+01,  1.51800000e+01,  1.57500000e+01],
         [ 1.53122000e+01,  1.52886000e+01,  1.55996000e+01],
         [ 1.40328200e+06,  1.12910324e+06,  1.93889272e+06],
         [ 2.60800000e-01, -1.30040000e+00,  3.75490000e+00],
         [ 7.42800000e-01,  5.97700000e-01,  1.02630000e+00],
         [ 1.50380000e+00,  1.21000000e+00,  2.07780000e+00]]]])

In [233]:
x_delay.shape
# data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
# l = []
# test_data = data[0][0].reshape(1,1,9,3)
# test_data
# for i in range(len(step_list)-1):
#     start = step_list[i]
#     end = step_list[i+1]
#     sub_data1 = data[:,:,:,start:end]
#     print(sub_data1.shape)
#     print(sub_data1[:,:,:,0].shape)
#     ret = sub_data1[:,:,:,-1]-sub_data1[:,:,:,0] - 1
#     l.append(ret)
# z_data = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,feat_num,len(step_list)-1)
# torch.from_numpy(z_data)

(1, 1, 9, 3)

In [3]:
data=np.random.uniform(10,100,(2000,1,9,30))

# feat_nums = data.shape[2]
# list1 = list(range(feat_nums))
# num = generateC(list1)
# num_rev = []
# for l in num:
#     l1 = l.copy()
#     l1.reverse()
#     num_rev.append(l1)
# print(num,'\n',num_rev)



len(num)

NameError: name 'num' is not defined

In [46]:
class Data:
    def __init__(self,data,stride):
        self.data = data
        self.stride = stride
        self.data_length = data.shape[3]
        self.feat_num = data.shape[2]
        self.num , self.num_rev = self.generate_Num(self.feat_num)
        self.conv_feat = len(self.num)
        self.step_list = self.get_step_list(self.data_length,self.stride)
    def generate_Num(self,feat_nums):
        num = []
        for i in range(feat_nums-1):
            for j in range(i+1,feat_nums):
                num.append([i,j])
        num_rev = []
        for l in num:
            l1 = l.copy()
            l1.reverse()
            num_rev.append(l1)
        return num , num_rev
    def get_step_list(self,data_length,stride):
        if data_length % stride == 0:
            step_list = list(range(0,data_length+stride,stride))
        elif data_length % stride<=5:
            mod = data_length % stride
            step_list = list(range(0,data_length-stride,stride))+[data_length]
        else:
            mod = data_length % stride
            step_list = list(range(0,data_length+stride-mod,stride))+[data_length]
        return step_list
one = Data(data,10)

In [146]:
stride = 10
# 为了cov 和 corr提取并行计算产生计算列表
def generateC(l1):
    if len(l1) == 1:
        return []
    v = [[l1[0],i] for i in l1[1:]]
    l1 = l1[1:]
    return v+generateC(l1)
def generate_Num_and_ReversedNum(feat_nums):
    list1 = list(range(feat_nums))
    num = generateC(list1)
    num_rev = []
    for l in num:
        l1 = l.copy()
        l1.reverse()
        num_rev.append(l1)
    return num , num_rev
def data_info(data,stride):
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length = data.shape[3] # 30
    feat_num = data.shape[2] # 9
    """num:组合数对列表,num_rev:num的翻转列表"""
    num , num_rev = generate_Num_and_ReversedNum(feat_num)
    conv_feat = len(num)
    # 构建步长列表，如果数据长度不能整除，则取剩下长度，如果剩下长度小于5，则与上一步结合一起
    if data_length % stride == 0:
        step_list = list(range(0,data_length+stride,stride))
    elif data_length % stride<=5:
        mod = data_length % stride
        step_list = list(range(0,data_length-stride,stride))+[data_length]
    else:
        mod = data_length % stride
        step_list = list(range(0,data_length+stride-mod,stride))+[data_length]
    return data_length,feat_num,conv_feat,num,num_rev,step_list
def ts_cov4d(data,stride):
    '''计算4维数据的协方差'''
    '''data:[N,C,H,W],,W:price length,N:batch size'''
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    #计算的过程中务必保持keepdims=True
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        sub_data1 = data[:,:,num,start:end] # (2000, 1, 36, 2, 10)
        sub_data2 = data[:,:,num_rev,start:end]
        mean1 = sub_data1.mean(axis = 4,keepdims = True) # (2000, 1, 36, 2, 1)
        mean2 = sub_data2.mean(axis = 4,keepdims = True)
        spread1 = sub_data1 - mean1 # (2000, 1, 36, 2, 10)
        spread2 = sub_data2 - mean2
        cov = ((spread1*spread2).sum(axis = 4,keepdims = True)/(sub_data1.shape[4] - 1)).mean(axis = 3,keepdims = True) # (2000, 1, 36, 1, 1)
        l.append(cov)
    corr = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,conv_feat,len(step_list)-1) # (2000, 1, 36, 3)
    return torch.from_numpy(corr)
def ts_corr4d(data,stride):
    '''计算4维数据的相关系数'''
    '''data:[N,C,H,W],,W:price length,N:batch size'''
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        sub_data1 = data[:,:,num,start:end]
        sub_data2 = data[:,:,num_rev,start:end]
        std1 = sub_data1.std(axis = 4,keepdims = True)
        std2 = sub_data2.std(axis = 4,keepdims = True)
        std = (std1*std2).mean(axis = 3,keepdims = True)
        l.append(std)
    std = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,conv_feat,len(step_list)-1)
    cov = ts_cov4d(data,stride)
    fct = (sub_data1.shape[4]-1)/sub_data1.shape[4]
    return (cov/torch.from_numpy(std))*fct

def ts_stddev4d(data,stride):
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        sub_data1 = data[:,:,:,start:end]
        std1 = sub_data1.std(axis = 3,keepdims = True)
        l.append(std1)
    std = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,feat_num,len(step_list)-1)
    return torch.from_numpy(std)
def ts_zscore(data,stride):
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        sub_data1 = data[:,:,:,start:end]
        mean = sub_data1.mean(axis = 3,keepdims = True)
        std = sub_data1.std(axis = 3,keepdims = True)
        z_score = mean/std
        l.append(z_score)
    z_score = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,feat_num,len(step_list)-1)
    return torch.from_numpy(z_score)
def ts_return(data,delay_data):
    """
    data = row data
    delay = 将数据回溯到delay的时间前
    """
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        sub_data1 = data[:,:,:,start:end]
        ret = sub_data1[:,:,:,-1]/sub_data1[:,:,:,0] - 1
        l.append(ret)
    z_data = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,feat_num,len(step_list)-1)
    return torch.from_numpy(z_data)

def ts_decaylinear(data,stride):
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        time_spread = end - start
        weight = np.arange(1,time_spread+1)
        weight = weight/(weight.sum())
        sub_data1 = (data[:,:,:,start:end]*weight).sum(axis = 3,keepdims = True)
        l.append(sub_data1)
    decay_data = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,feat_num,len(step_list)-1)
    return torch.from_numpy(decay_data)
def ts_pool(data,stride,method):
    if type(data) == torch.Tensor:
        data = data.detach().numpy()
    if data.shape[-1] <= stride:
        step_list = [0,data.shape[-1]]
    if len(data.shape)!=4:
        raise Exception('Input data dimensions should be [N,C,H,W]')
    data_length , feat_num , conv_feat, num , num_rev,step_list= data_info(data,stride)
    l = []
    for i in range(len(step_list)-1):
        start = step_list[i]
        end = step_list[i+1]
        if method == 'max':
            sub_data1 = data[:,:,:,start:end].max(axis = 3,keepdims = True)
        if method == 'min':
            sub_data1 = data[:,:,:,start:end].min(axis = 3,keepdims = True)
        if method == 'mean':
            sub_data1 = data[:,:,:,start:end].mean(axis = 3,keepdims = True)
        l.append(sub_data1)
    try:
        pool_data = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,feat_num,len(step_list) - 1)
    except:
        pool_data = np.squeeze(np.array(l)).reshape(-1,1,feat_num,len(step_list) - 1)
    return torch.from_numpy(pool_data)

In [207]:
one_data

,,open,high,low,close,vwap,volume,pct_chg,turnover,free_turnover,pct_change_shift
timestamp,ticker,,,,,,,,,,
2019-09-23,1,15.34,15.47,15.18,15.38,15.3122,1403282.00,0.2608,0.7428,1.5038,2.405722
2019-09-24,1,15.47,15.54,15.18,15.18,15.2886,1129103.24,-1.3004,0.5977,1.2100,3.491436
2019-09-25,1,15.20,15.85,15.19,15.75,15.5996,1938892.72,3.7549,1.0263,2.0778,0.952381
2019-09-26,1,15.86,16.04,15.66,15.71,15.8491,1686592.58,-0.2540,0.8928,1.8074,-0.763845
2019-09-27,1,15.85,16.00,15.70,15.90,15.8634,1007706.27,1.2094,0.5193,1.0235,1.886792
...,...,...,...,...,...,...,...,...,...,...,...
2021-09-15,1,19.31,20.99,19.19,19.52,19.4779,841618.41,0.7744,0.4337,0.9785,-5.071721
2021-09-16,1,19.30,19.50,18.73,19.08,18.9852,1176953.56,-2.2541,0.6065,1.3684,-5.765199
2021-09-17,1,18.90,19.00,18.41,18.53,18.6572,1124879.63,-2.8826,0.5797,1.3078,-4.587156
2021-09-22,1,17.87,18.05,17.42,17.98,17.7601,1473365.21,-2.9682,0.7592,1.7130,NaN
2021-09-23,1,18.10,18.32,17.65,17.68,17.8694,1379837.59,-1.6685,0.7110,1.6043,NaN

In [175]:
data = x
batch = nn.BatchNorm2d(1,affine=True)
conv1 = ts_cov4d(data,10).to(torch.float)
bc1 = batch(conv1)
conv2 = ts_corr4d(data,10).to(torch.float)
bc2 = batch(conv2)
conv3 = ts_stddev4d(data,10).to(torch.float)
bc3 = batch(conv3)
conv4 = ts_decaylinear(data,10).to(torch.float)
bc4 = batch(conv4)
conv5 = ts_zscore(data,10).to(torch.float)
bc5 = batch(conv5)
conv6 = ts_return(data,10).to(torch.float)
bc6 = batch(conv6)
conv6.shape
# feat_cat = torch.cat([bc1,bc2,bc3,bc4,bc5,bc6],axis = 2) # 特征聚合


# # Pooling
# ts_max = ts_pool(feat_cat ,3,method = 'max')
# ts_max = batch(ts_max)
# ts_min = ts_pool(feat_cat ,3,method = 'min')
# ts_min = batch(ts_min)
# ts_mean = ts_pool(feat_cat ,3,method = 'mean')
# ts_mean = batch(ts_mean)
# data_pool = torch.cat([ts_max,ts_min,ts_mean],axis = 2)
# data_pool = data_pool .flatten(start_dim = 1)
# print(data_pool.shape)
# pipline = nn.Sequential(nn.Linear(324,30),
#                         nn.ReLU(),
#                       nn.Dropout(0.5),
#                        nn.Linear(30,1))
# output = pipline(data_pool)
# print(output,'\n',output.size())

C:\Users\Xinfei\AppData\Local\Temp/ipykernel_15068/209828363.py:115: RuntimeWarning: divide by zero encountered in true_divide
  ret = sub_data1[:,:,:,-1]/sub_data1[:,:,:,0] - 1

torch.Size([153, 1, 9, 3])

In [23]:
cov = ts_corr4d(data,10)
cov.shape

torch.Size([2000, 1, 36, 3])

In [29]:
data = np.random.uniform(10,100,(2000,1,9,30))#随机产生2000只股票的数据图片
ts_cov = ts_corr4d(data,num,num_rev,10)
print(ts_cov.shape)

torch.Size([2000, 1, 36, 3])